### ISSUE TITLE
Add other types of triggers rather than binary switch

### ISSUE THREAD

**Issue by Serhioromano** [nielsfaber/alarmo#755] opened 2023-06-30 13:28 UTC
I have few temperature sensors around my house. I have smoke detectors, yes, but if temperature raises to 60 degree Celsius, I may be certain that there is some fire. I want alarm to be triggered with those conditions too.

Possible to add more complex conditions to sensors?

If i add automation and trigger the built in HA alarm, will it work? Will your alarm be triggered?

**Comment by nielsfaber** [comment] 2023-07-01 15:24
Duplicate of https://github.com/nielsfaber/alarmo/issues/184

**Closed by nielsfaber** 2023-07-01 15:24 UTC
Labels: feature_request
