### ISSUE TITLE
Can't add users when alarm is on

### ISSUE THREAD

**Issue by stefanolson** [nielsfaber/alarmo#5] opened 2020-11-01 03:23 UTC
Turn the alarm on from the overview page. Then try and add a user in the alarm panel page and click save and doesn't save. Turn the alarm off and it will save. The behaviour is probably correct it's just a bit confusing, so would be good if there was a message to say it wasn't able to be added.

**Comment by nielsfaber** [comment] 2020-11-01 05:26
This is indeed intended.
You cannot make changes to the alarm while it is active.
Both for security reasons and because it would make the code quite more complex.

> so would be good if there was a message to say it wasn't able to be added.

This is a limitation of HA. Cannot get any feedback after clicking a button, because it executes a service call (which are fire-and-forget).
I'm working on a completely different architecture that should improve this.

**Comment by nielsfaber** [comment] 2020-11-24 04:46
I'm closing this issue because I think the problem is solved now.

**Closed by nielsfaber** 2020-11-24 04:46 UTC
Labels: bug
