### ISSUE TITLE
I can't disable push messages

### ISSUE THREAD

**Issue by Sag06** [nielsfaber/alarmo#8] opened 2020-11-05 12:59 UTC
I enabled push messages and now I can't disable them. I tried to refresh cache browser, etc but push messages are enabled each time I check them. Doesn't mind if I vary "target for push messages" option.

**Comment by Necrolust** [comment] 2020-11-14 21:53
I also have this issue on the same section of Alarmo, but with the enable siren device.

I can change the device to be triggered and it saves the changes but not for enabling the siren device. That is stuck as enabled now - same as @Sag06 with the push messages checkbox.

**Comment by nielsfaber** [comment] 2020-11-16 17:17
Please try out v1.1.0.
It should solve this issue.

As for siren devices: they are not implemented yet.. Will come in a bit.

**Comment by Necrolust** [comment] 2020-11-16 19:40
Great I'll try it today and report back.

By the way - keep up the good work. This is literally the perfect replacement for BW Alarm and is everything I could have hoped for that the manual alarm cannot provide.

**Comment by Necrolust** [comment] 2020-11-19 05:58
Can confirm push notification enabling and disabling works.

I see you have removed the switching functionality :) eagerly awaiting this so I can manage it from UI and get rid of yet another automation in YAML.

**Comment by nielsfaber** [comment] 2020-11-19 06:00
> I see you have removed the switching functionality :) eagerly awaiting this 

Sorry, what do you mean with this? 
I have no intentions of removing features..

**Comment by Necrolust** [comment] 2020-11-19 06:03
Ah.

Before there was the option to enable a siren but it was stuck as enabled after the first time enabling it.

You stated that switching functionality was coming later, I thought you had left it in the other release as a mistake because now it says coming soon

**Comment by nielsfaber** [comment] 2020-11-19 06:07
Oh that.
Yup, it will roughly look the same as the notification UI.
But I didn’t find the time yet for making and testing it. 
Its high on my agenda though.

**Comment by nielsfaber** [comment] 2020-11-24 17:08
I'm closing this issue because the issue is resolved.
Feel free to open a new item if you are missing some functionality.

**Closed by nielsfaber** 2020-11-24 17:08 UTC
Labels: bug
