### ISSUE TITLE
Notification action not executed on "Alarm is triggered" event

### ISSUE THREAD

**Issue by ieno** [nielsfaber/alarmo#376] opened 2022-01-18 17:27 UTC
### Alarmo Version

v1.8.3

### HA Version

2021.12.10

### Bug description

After defining multiple notification actions, the ones that are configured to trigger on the "Alarm is triggered" event, do not appear to be triggered whenever "{{open_sensors}}" is added to the message (format doesn't matter). When using the "TEST" button, they do work.

When looking at the state of the "master" area when the alarm is triggered, it does change (and the actions are also triggered):
```
topic: "alarm_control_panel.master"
payload: "triggered"
```

To rule out this was related to the master area, I also specifically created notifications for all the other areas, these also do not trigger on the "Alarm is triggered" event when "{{open_sensors}}" is part of the message. When the message does not contain "{{open_sensors}}", it works fine.

### Steps to reproduce

Navigate to Alarmo > Actions
Add a new notification
Event: Alarm is triggered, area: any
Task:
```
service: notify.telegram
service_data:
  title: ''
  message: Test {{open_sensors}}
```

//edit
It seems to be Telegram specific, and has to do with underscores (perhaps there are more characters, used for formatting I presume) being in the sensor name. If an uneven number of underscores are present, the message will not arrive.

**Comment by Patrick44fr** [comment] 2022-01-22 08:56
hello,
 I get the same problem with an audio message, by research by the development tools, the service call is:
```
service: notify.telegram
data: (not service_data)
  title: '
  message: Test {{open_sensors}}
```
can be a track to dig that will help, it's the same for audio message, service_data don't work

**Comment by nielsfaber** [comment] 2022-02-02 04:32
Duplicate of https://github.com/nielsfaber/alarmo/issues/266

**Closed by nielsfaber** 2022-02-02 04:32 UTC
Labels: bug

**Comment by depuits** [comment] 2022-02-02 10:31
This is a home assistant issue with the telegram notifier. More information can be found here: https://github.com/home-assistant/core/issues/45290.
