### ISSUE TITLE
Support of non binary sensors

### ISSUE THREAD

**Issue by ChristophCaina** [nielsfaber/alarmo#957] opened 2024-06-02 00:34 UTC
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
There are sensors for windows that report the current position of a window handle.
Theres sensors are no binary_sensors, since they do report the state: "closed", "open" or "tilted".
I would like to use those sensors in Alarmo, since the binary sensor would report a window as closed, if it is leaning, but the handle is not closed.

The only solution right now would be, to create a binary_sensor template, which will report an "open" state for the "Open" or "Tilted" state of the origin sensor.
Having such sensor support natively in alarmo would allow a more precise configuration.

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment] 2024-06-02 04:50
Duplicate of #755 and #184

**Closed by nielsfaber** 2024-06-02 04:50 UTC
Labels: feature_request
