### ISSUE TITLE
Error in log with latest hass docker beta

### ISSUE THREAD

**Issue by pvklink** [nielsfaber/alarmo#875] opened 2024-01-12 13:09 UTC
### Alarmo Version

v1.9.13

### HA Version

ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2024.2.0.dev20240110

### Bug description

part of my log

2024-01-12 13:26:16.891 WARNING (MainThread) [homeassistant.components.alarm_control_panel] FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues
2024-01-12 13:26:16.901 WARNING (MainThread) [homeassistant.components.alarm_control_panel] FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues

### Steps to reproduce

reboot hass

### Relevant log output

```shell
ssss
```

**Comment by IceBotYT** [comment] 2024-01-13 01:54
Dupe of #864

**Comment by nielsfaber** [comment] 2024-01-17 19:26
Your log reports _warnings_, no _errors_.
These will be removed in the next release.

**Closed by nielsfaber** 2024-01-17 19:26 UTC
Labels: bug
