### ISSUE TITLE
Error starting Alarmo

### ISSUE THREAD

**Issue by robwiklu** [nielsfaber/alarmo#886] opened 2024-01-28 14:31 UTC
### Alarmo Version

v1.9.14

### HA Version

2024.1.5

### Bug description

A few days ago i got an error on my Alarmo Card about the entity. I looked at the log (see attached log after a full removal/new installation). I tried restarting HA, uninstalling/installing Alarmo but to no avail.

### Steps to reproduce

Uninstall/reinstalling Alarmo from Integrations and HACS. Reboot. Install in HACS, install in Integrations. Same problem.

### Relevant log output

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 15:26:07 (1 occurrences)
Last logged: 15:26:07

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/__init__.py", line 56, in async_setup_entry
    store = await async_get_registry(hass)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alarmo/store.py", line 691, in async_get_registry
    return cast(AlarmoStorage, await task)
                               ^^^^^^^^^^
KeyError: 'sensor_groups'
```

**Comment by nielsfaber** [comment] 2024-01-28 14:54
Duplicate of #882

**Closed by nielsfaber** 2024-01-28 14:54 UTC
Labels: bug
