### ISSUE TITLE
Opening door sensor during exit delay

### ISSUE THREAD

**Issue by g1za** [nielsfaber/alarmo#666] opened 2023-02-22 07:15 UTC
### Alarmo Version

v1.9.7

### HA Version

2023.2.5

### Bug description

Hello,
When arming away, during the exit delay, if I open the door to leave, this will prevent the alarm from arming. 
Shouldn’t I be allowed to leave, the sensors not being watched during the leave delay, and only at the end the alarm be armed (or not, depending on the sensors state and “skip open sensors” setting)?
Did I misinterpret the exit delay expected behaviour?
Thank you

### Steps to reproduce

Arm away with exit delay, open the door during the delay (and if you want close it, but it’s not relevant). This will prevent the alarm from arming.

**Comment by nielsfaber** [comment] 2023-02-22 07:28
> Shouldn’t I be allowed to leave, the sensors not being watched during the leave delay, and only at the end the alarm be armed (or not, depending on the sensors state and “skip open sensors” setting)?

Depends on how you configured your sensors.
You can set per sensor whether it is allowed to be active during the exit and/or entry delay.
Not a bug, closing issue.

**Closed by nielsfaber** 2023-02-22 07:28 UTC
Labels: bug
