### ISSUE TITLE
Panel on toolbar display "loading..." instead of alarmo configuration

### ISSUE THREAD

**Issue by guillaumetournabien** [nielsfaber/alarmo#711] opened 2023-04-28 08:59 UTC
### Alarmo Version

V1.9.9

### HA Version

2023.4.6

### Bug description

After update with 1.9.9, the Alarmo screen (icone Alarmo on HA) display 'loading...' on the top and no access to the configuration information of alarmo.
Nevertheless, the Alarmo is working, I can enable or disable with loveplace screen.

Tried to disable and enable the module (still issue)
Tried to download the ZIP again and rewrite the files (still issue)

Any idea ?

My configuration (RPI4)
Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Interface utilisateur : 20230411.1 - latest 

### Steps to reproduce

Just click on Alarmo icon the left toolbar

**Comment by alekso56** [comment] 2023-04-30 01:48
This is normal, clear your cache, you have outdated files for your installation.

You might see things like " :0:0 ResizeObserver loop completed with undelivered notifications" in your HA logs.

**Comment by guillaumetournabien** [comment] 2023-04-30 09:33
Thanks a lot

**Comment by ADX88** [comment] 2023-04-30 13:27
I got this issue also

**Comment by sknsean** [comment] 2023-04-30 17:34
I still have this issue even after clearing cache in the home assistant app (iOS) and firefox browser cache on PC.

**Comment by nielsfaber** [comment] 2023-04-30 18:16
Duplicate of #688

**Closed by nielsfaber** 2023-04-30 18:16 UTC
Labels: bug
