### ISSUE TITLE
Blank Action Page

### ISSUE THREAD

**Issue by StepG38** [nielsfaber/alarmo#373] opened 2022-01-16 13:31 UTC
### Alarmo Version

V1.8.2

### HA Version

2021.12.8

### Bug description

![Capture d’écran 2022-01-16 030058](https://user-images.githubusercontent.com/38179281/149662014-ae4036f2-ebee-4fc9-9f29-fad0409fa46b.jpg)
![Capture d’écran 2022-01-16 025840](https://user-images.githubusercontent.com/38179281/149662024-c78f4b2c-d7c0-496d-ad41-b57133bb967d.jpg)
Hello,
I just installed Alarmo.
I can create an action that works but cannot modify it afterwards. The page is blank.
Thanks for your help
Stephane

**Comment by nielsfaber** [comment] 2022-01-16 13:32
Duplicate of https://github.com/nielsfaber/alarmo/issues/369

**Closed by nielsfaber** 2022-01-16 13:32 UTC
Labels: bug

**Comment by StepG38** [comment] 2022-01-16 13:39
bonjour @nielsfaber 
Is there a solution to the blank page of Actions?

**Comment by StepG38** [comment] 2022-01-17 04:28
Merci pour la nouvelle version !!
