### ISSUE TITLE
Continuously loading page appearing

### ISSUE THREAD

**Issue by sabricakmak** [nielsfaber/alarmo#855] opened 2023-12-10 18:30 UTC
### Alarmo Version

V1.9.13

### HA Version

2023.12.1

### Bug description

When i tried to open Alamo configuration page just appearing loading line. I attached screen copy. I restarted HA, reinstall Alarmo but result is same. What should i do. 
![IMG_1396](https://github.com/nielsfaber/alarmo/assets/98055172/930f9284-58bd-42be-8d34-d78ffa07cb6c)

### Steps to reproduce

Updated HA, Alarmo and Hacs

**Comment by sabricakmak** [comment] 2023-12-10 18:53
Same problem crated by an other user under “Configuration page stuck on 'loading...' #807” this topic. Therefor i am closing this issue

**Comment by nielsfaber** [comment] 2023-12-27 05:33
duplicate of #807

**Closed by nielsfaber** 2023-12-27 05:33 UTC
Labels: bug
