### ISSUE TITLE
HA Version 2022.6.0 - Depreciated 'async_get_registry' , use 'async_get' instead

### ISSUE THREAD

**Issue by Tx-ST-Home** [nielsfaber/alarmo#487] opened 2022-06-02 11:05 UTC
### Alarmo Version

1.9.3

### HA Version

2022.6.0

### Bug description

After upgrading my instance of HA to 2022.6.0 I noted a WARNING in the system log. See the Relevant log output section below.  
async_get_registry has been depreciated and replaced with async_get. 

### Steps to reproduce

Upgrade my instance of HA to 2022.6.0

### Relevant log output

```shell
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: June 1, 2022, 11:09:47 AM (1 occurrences)
Last logged: June 1, 2022, 11:09:47 AM

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 58: device_registry = await dr.async_get_registry(hass)
```

**Comment by nielsfaber** [comment] 2022-06-02 11:13
Duplicate of #475

**Closed by nielsfaber** 2022-06-02 11:13 UTC
Labels: bug
