### ISSUE TITLE
Feature request: Alarm zones

### ISSUE THREAD

**Issue by i-o-m-a** [nielsfaber/alarmo#78] opened 2020-12-23 23:14 UTC
Hello,

Is it possible to have different zones, that can be armed and disarmed separately? For example 1 zone - home, 2 zone - depot, and etc.?

**Comment by nielsfaber** [comment] 2020-12-24 06:08
Duplicate of https://github.com/nielsfaber/alarmo/issues/25
This is a work-in-progress

**Closed by nielsfaber** 2020-12-24 06:08 UTC
