### ISSUE TITLE
Sensor device type

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#370] opened 2022-01-15 16:58 UTC
### Alarmo Version

v1.8.2

### HA Version

2021.12.9

### Bug description

Binary sensors with device type "problem" are recognized as device type "tamper" by Alarmo.

### Steps to reproduce

- customize any binary sensor to device type "problem"
- device shows up in Alarmo as device type "tamper"

**Comment by nielsfaber** [comment] 2022-01-16 07:09
This is not a bug, this is done [by design](https://github.com/nielsfaber/alarmo/blob/main/custom_components/alarmo/frontend/src/data/sensors.ts#L62). 
However I have no idea what is the intended usage of 'problem' binary_sensors. 
There is no documentation in HA about this.
If you think it belongs better to another category, please let me know.

**Comment by Eyco1981** [comment] 2022-01-16 07:19
E.g. Shelly devices use the "problem" device type for overtemperature or overload states. Ring uses it for software failure indications.
In my opinion, those binary sensors shouldn't be shown by default. If needed, they could be selected from the hidden ones.
But it's just my opinion.

**Comment by nielsfaber** [comment] 2022-01-16 17:59
should be fixed in v1.8.3

**Closed by nielsfaber** 2022-01-16 17:59 UTC
Labels: bug
