### ISSUE TITLE
feature request, activation not at home and deactivation at home domain "person."

### ISSUE THREAD

**Issue by Ausonius** [nielsfaber/alarmo#86] opened 2021-01-04 22:00 UTC
Hi I have an integration that you could add to the alarm, in practice through the frontend to include or exclude the people added in HA through the domain "person.ciccio person.eva etc ..", for the activation of the alarm when you leave the house , I am sending you the files of the automation I am using, which you could insert in the alarmo interface.

pastebin https://pastebin.com/FzvupUR1

**Comment by nielsfaber** [comment] 2021-01-05 09:15
If i understand your request correctly, you want to add the functionality to automatically arm the alarm based on an event in an external device or entity (geofencing).
So far Alarmo only offers functionality the other way around: you can choose what to do when something changes in the alarm.

I'm a bit puzzling with how to further improve the internal 'actions' of Alarmo.
I'm getting a lot of requests for advanced features. 
It seems that the desired functionality is very user-dependent, so it will be difficult to satisfy all needs.
My intention was to help people program simple tasks, not to create a duplicate of the HA automations functionality.

Recently HA added the blueprints functionality.
It seems a great way to help users set up and maintain automations in a simple way, and it has the option for creating more advanced tasks.
Maybe we could develop a set of blueprints for Alarm(o) and share these between the users?
I could also investigate if I could add functionality to import blueprints into Alarmo directly. 
It seems more future-proof than keeping improving the internal editor.
What do you think?

**Comment by Ausonius** [comment] 2021-01-05 15:30
yes the code i sent you i'm using it with alarmo and it works fine, besides there is also need of another file (group_people_allowed_alarm.yml) that starts the shell for the insertion and deactivation of people who are already added in HA.

It would be a great idea that instead of creating a user, to arm and disarm the users who are present as domain (person.x) in HA, leave the section of the (PIN), and also add the section (geofencing) with the range option.

your idea is excellent, to make a section where you can import automations such as bluespirit where you can create your own automations

another thing I did not understand how to add an alarm for the night mode could you tell me?

I'm sorry for my English and I use the translator a bit

**Comment by quizzical86** [comment] 2021-01-05 15:32
Yes I would fully agree that Alarmo focuses on the core functionalities and while these 'blueprints' come too late for me (I'm already addicted to Node Red now) they seem like an excellent solution for others to share automations around alarmo (I hope these blueprints can be used as a basis and then customised by those users willing to go a bit further, as it will indeed be difficult to cover all the peculiar needs of each user).

**Comment by nielsfaber** [comment] 2021-01-29 22:23
As discussed, I don’t think this feature is really needed in Alarmo.
The HA automations/blueprints offer sufficient options to accomplish this.

**Closed by nielsfaber** 2021-01-29 22:23 UTC
Labels: wontfix
