### ISSUE TITLE
HA updatet to core-2021.5.0b3, Alarmo won t start

### ISSUE THREAD

**Issue by martin82private** [nielsfaber/alarmo#192] opened 2021-04-30 12:48 UTC
Hi
i updated to the latest Beta Version of HA core-2021.5.0b3. Now Alarm won t start:

Logger: homeassistant.config_entries
Source: custom_components/alarmo/card.py:37
Integration: Alarmo (documentation, issues)
First occurred: 14:43:04 (1 occurrences)
Last logged: 14:43:04

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'

**Comment by nielsfaber** [comment] 2021-04-30 14:33
Duplicate of #186 #189 #190 #191.
Please look for other issues before opening one.

Youre running a beta release, so there is always this risk.

**Closed by nielsfaber** 2021-04-30 14:33 UTC
