### ISSUE TITLE
Sending a notification at entering again while my alarm is already off.

### ISSUE THREAD

**Issue by GeeGee-be** [nielsfaber/alarmo#784] opened 2023-08-16 12:22 UTC
### Alarmo Version

v1.9.1

### HA Version

2023.8.2

### Bug description

I've put in a notification in the Alarmo action settings to send me a warning that my alarm will trigger when entering my home if it's armed home or away. So even when I'm at home and open a door it will send me the notification.
When I open a door (or any other sensor that is configured in Alarmo) it puts the alarm in pending and I get the notification. So far so good.
When disarming I also get a notification that it is disarmed.
But (I guess) at about 1 minute later I get again the message that I has when it turned into pending status. And the alarm is already disarmed.
What can be the cause? I'm thinking it's a bug since all settings look fine.

### Steps to reproduce

Set a message to send when in pending (entering) status. Don't select a mode, so in fact it should do it while at home and away.
Than turn the alarm on and trigger it to pending status by opening a door or whatever sets this trigger.

**Comment by GeeGee-be** [comment] 2023-08-17 07:06
Dear, I found the issue that can cause this problem. When running scripts in the actions that contain wait functions, it will cause issues in Alarmo notifications. So the wait functions in the script will cause delay's in Alarmo. You can solve this by setting your actions in automations (tested and ok) and/or you change the scripts mode (need to test this).

**Comment by nielsfaber** [comment] 2023-08-17 07:21
I was not aware of this.
Alarmo should execute all actions in parallel, without delays.
I think you found a bug and it does need to be addressed.

**Comment by nielsfaber** [comment] 2023-08-23 07:53
I found the cause of the issue and fixed it (https://github.com/nielsfaber/alarmo/commit/0b933d65c44cc630adb46bf8fd1e5f67ef6eed66).
This will be part of the next release.

**Closed by nielsfaber** 2023-08-23 07:53 UTC
Labels: bug
