### ISSUE TITLE
400 error when trying to add or edit a notification

### ISSUE THREAD

**Issue by kasdewit21** [nielsfaber/alarmo#547] opened 2022-08-06 11:45 UTC
### Alarmo Version

v1.9.3

### HA Version

2022.8.1

### Bug description

400 error when trying to add or edit a notification.

Something went wrong!
Message format incorrect: extra keys not allowed @ data['actions'][0]['service_data']

Response error: 400

### Steps to reproduce

1. Alarmo > Actions > New notification
2. Add a simple notification filling only mandatory fields
3. Click save and error turns up

### Relevant log output

```shell
2022-08-06 13:40:48.208 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['actions'][0]['service_data']
2022-08-06 13:42:55.088 ERROR (MainThread) [homeassistant.components.http.data_validator] Data does not match schema: extra keys not allowed @ data['actions'][0]['service_data']
```

**Comment by nielsfaber** [comment] 2022-08-06 11:53
Duplicate of #541.

**Closed by nielsfaber** 2022-08-06 11:53 UTC
Labels: bug
