### ISSUE TITLE
Entity not available: alarm_control_panel.alarmo

### ISSUE THREAD

**Issue by ygreq** [nielsfaber/alarmo#655] opened 2023-01-28 09:42 UTC
### Alarmo Version

v1.9.7

### HA Version

2023.1.7

### Bug description

It used to work. I don't know what changed, but now the Alarmo entity in Lovelace does not work anymore. It gives me this error: Entity not available: alarm_control_panel.alarmo instead of the actual entity. 
![alarmo](https://user-images.githubusercontent.com/2974241/215259020-2830d698-5fca-4e45-85c1-f46458fd2c21.PNG)

Everything else seems to work alright.

Thank you!

### Steps to reproduce

Many things changed since I know it was working. I installed different versions on HA. I don't know if a newer version of HA broke the entity. 

### Relevant log output

```shell
I don't know where to get the log for Alarmo from.
```

**Comment by nielsfaber** [comment] 2023-01-30 16:07
Please check the developer tools -> states for the alarm_control_panel entities and find which one belongs to alarmo.
You might have changed the area name, this causes the entity name to be updated as well.

**Comment by julian100004** [comment] 2023-01-31 09:11
I had the same problem. 
For me it changed the name to "alarm_control_panel.alarmo_2" for some reason. 
I just renamed it back and now it's working again.

**Comment by ygreq** [comment] 2023-01-31 09:54
Thank you so much to both of you. I realized alarm_control_panel.alarmo was renamed to alarm_control_panel.entry. No idea why.  

I renamed it and everything works just fine now.

**Comment by julian100004** [comment] 2023-01-31 10:01
You probably renamed the area from "Alarmo" to "Entry" in the Alarmo settings.

![image](https://user-images.githubusercontent.com/21989955/215728827-24adedd3-79de-4592-a56f-cf999df38a20.png)

Glad you got it fixed now 😄

**Comment by ygreq** [comment] 2023-01-31 13:12
Yeap. I guess this is what I did. BTW, I renamed the entity back to Alarmo, but I see that the area is still named Entry. Maybe there is a bug where when you rename the area, it renames the entity as well. At least this is what I understand. :)

**Comment by julian100004** [comment] 2023-01-31 14:52
It's not a bug 😅 that's how it's supposed to be

**Comment by ygreq** [comment] 2023-02-01 09:27
I get it now. I should have created a new zone. 

Thank you so much!!

**Closed** 2023-02-01 09:28 UTC
Labels: bug
