### ISSUE TITLE
Action mode limit not working for alarm disarmed event

### ISSUE THREAD

**Issue by datbilling** [nielsfaber/alarmo#438] opened 2022-04-05 12:05 UTC
### Alarmo Version

v1.8.7

### HA Version

2022.3.8

### Bug description

It seems the condition mode is not not working for actions that have an event condition of 'Alarm is disarmed'.

I have an 'Action' with an event condition of 'Alarm is disarmed' and the 'Mode' limit is set to 'Away'.

However, the action is triggered when disarming from any mode e.g. 'Armed home' or 'Armed night'. I only want it to trigger when disarming from 'Armed away' mode. 

### Steps to reproduce

I created an 'Action' with an event condition of 'Alarm is disarmed'. 
The 'Mode' limit is set to 'Away'. 
The task is to announce 'Alarm disarmed' on amazon echo devices using Alexa TTS.
I set alarmo to 'Armed home' mode.
I then disarm the alarm.
The action is then triggered, when I only expect it to if I was previously in 'Armed away' mode.

![image](https://user-images.githubusercontent.com/58982799/161749889-db21fdda-80d9-4f8d-8073-3319c6507439.png)

**Comment by nielsfaber** [comment] 2022-04-05 17:45
Duplicate of https://github.com/nielsfaber/alarmo/issues/365

**Closed by nielsfaber** 2022-04-05 17:45 UTC
Labels: bug
