### ISSUE TITLE
Failed to call service. Cannot Disarm

### ISSUE THREAD

**Issue by Lazymtl** [nielsfaber/alarmo#962] opened 2024-06-06 04:16 UTC
### Alarmo Version

V1.10.1

### HA Version

2024.6

### Bug description

I have an automation that arms home when I go to sleep. 

When trying to disarm, i get an error saying failed to call service x (see screenshot attached)

this issue only happened after updating alarmo

### Steps to reproduce

After updating alarmo to today’s latest version, i get an error failed to call service x (see screenshot)
![IMG_6716](https://github.com/nielsfaber/alarmo/assets/151051645/1c54b378-9b77-45cf-a878-6be1cdd2fe26)

**Comment by nielsfaber** [comment] 2024-06-06 04:18
Duplicate of #952

**Closed by nielsfaber** 2024-06-06 04:18 UTC
Labels: bug
