### ISSUE TITLE
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9

### ISSUE THREAD

**Issue by mirml** [nielsfaber/alarmo#1028] opened 2024-09-15 04:15 UTC
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

2.0.1

### HA Version

2024.9.1

### Bug description

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 06:10:14 (2 occurrences)
Last logged: 06:10:14

Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues

### Steps to reproduce

Checked log

**Comment by smarthomefamilyverrips** [comment] 2024-09-17 09:40
Same warning message in logs

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 12:19:13 (2 occurrences)
Last logged: 12:19:13

Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues

**Comment by MajorAutomation** [comment] 2024-09-20 23:36
Same issue

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 09:02:41 (4 occurrences)
Last logged: 09:02:41

Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues

**Comment by codyc1515** [comment] 2024-09-30 20:16
Duplicate of #1020

**Comment by nielsfaber** [comment] 2024-10-06 05:27
Sorry for the delay, this is now fixed (https://github.com/nielsfaber/alarmo/commit/fdbbb35bffccfef9a8d550889c89fd2f7c5d0593) and will be released soon.

**Closed by nielsfaber** 2024-10-06 05:27 UTC
Labels: bug
