### ISSUE TITLE
Alarmo card not recognized after HA update to core-2021.6.1

### ISSUE THREAD

**Issue by CharlesGitHib** [nielsfaber/alarmo#221] opened 2021-06-04 05:03 UTC
core-2021.6.1

**Comment by jasonwragg** [comment] 2021-06-04 08:14
Same issue on core-2021.6.0

**Comment by nielsfaber** [comment] 2021-06-04 15:12
I am here on 2021.6.1 as well:
![image](https://user-images.githubusercontent.com/16861605/120823581-db7a8b00-c557-11eb-9c20-d07f15d6b573.png)
But no problems for alarmo-card:
![image](https://user-images.githubusercontent.com/16861605/120823711-fc42e080-c557-11eb-9fe9-2262cababadd.png)

I don't really know how to help.

**Comment by CharlesGitHib** [comment] 2021-06-04 19:12
I returned back to v5.5 and run a direct upgrade to 6.1 and now the card is working again.FYI.

**Comment by Tosko4** [comment] 2021-06-04 19:12
Are there errors in the logs? Some more details could help clarify things better

**Comment by jasonwragg** [comment] 2021-06-05 14:43
Is not something to do with this?

https://developers.home-assistant.io/blog/2021/05/19/lit-2.0

Reported in the breaking changes?

**Comment by Tosko4** [comment] 2021-06-05 15:41
I am eager to upgrade. Don't want any trouble just yet lol. Rebuilding my HA environment. Dont want to be doing rollbacks etc. 

@nielsfaber what do you think?

**Comment by CharlesGitHib** [comment] 2021-06-05 17:14
> Same issue on core-2021.6.0

I just upgraded my HA to 6.2 and it's working fine. The frontend also was updated. Try to reset the browser cache and see if that works.

**Comment by nielsfaber** [comment] 2021-06-05 20:05
I am not aware of any problems with Alarmo-card.
I think clearing browser cache may solve the problem (this has been the cause many times in the past)

**Comment by Tonvandermark** [comment] 2021-06-06 09:37
After upgrading to core-2021.6.x get error message Wrong code provided. Code has not been changed and i reentered the code, now result.
Logger: custom_components.alarmo.alarm_control_panel
Source: custom_components/alarmo/alarm_control_panel.py:379
Integration: Alarmo (documentation, issues)
First occurred: 11:33:25 AM (1 occurrences)
Last logged: 11:33:25 AM

Wrong code provided.

**Comment by Smiley1244** [comment] 2021-06-06 21:16
I also get the 'Custom element doesn't exist: alarmo-card.' in the Android HA companion app, shows fine in Chrome. No log entries shown.

**Comment by nielsfaber** [comment] 2021-06-09 05:20
Closing this issue since the problems are due to browser caching and not a bug in the implementation.
Caching is behaviour of HA itself, I cannot help it.

**Closed by nielsfaber** 2021-06-09 05:20 UTC
