### ISSUE TITLE
Error when trying to edit a notification - Alarmo 1.6

### ISSUE THREAD

**Issue by SmartM-ui** [nielsfaber/alarmo#228] opened 2021-06-10 11:41 UTC
Something went wrong!
Message format incorrect: string value is None for dictionary value @ data['actions'][0]['entity_id']

Response error: 400

Please report the bug. 

In yaml mode I can see that it reports a null in entity_id:

service: notify.mobile_app_sm_n975u1
entity_id: null
service_data:
  title: Failure
  message: 'The alarm could not be armed right now, due to: {{open_sensors}}.'
  data:
    actions:
      - action: ALARMO_RETRY_ARM
        title: Retry Arm
      - action: ALARMO_FORCE_ARM
        title: Force Arm
    ttl: 0
    priority: high

**Comment by nielsfaber** [comment] 2021-06-10 11:56
Duplicate of https://github.com/nielsfaber/alarmo/issues/223

**Closed by nielsfaber** 2021-06-10 11:56 UTC
