### ISSUE TITLE
MQTT commands failing

### ISSUE THREAD

**Issue by tremebundo** [nielsfaber/alarmo#119] opened 2021-01-29 18:59 UTC
After upgrading to 1.5.1, I still have the same problem as in #117.
This is what appears at the log when I try to arm home with MQTT Alarm panel:

```
2021-01-29 19:50:27 ERROR (MainThread) [homeassistant.util.logging] Exception in async_message_received when handling msg on 'alarmo/command': 'ARM_HOME'
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 167, in async_message_received
    entity = self.hass.data[const.DOMAIN]["areas"].values()[0]
TypeError: 'dict_values' object is not subscriptable
```

**Comment by nielsfaber** [comment] 2021-01-29 19:48
I saw I made a mistake in the fix:
```
    entity = self.hass.data[const.DOMAIN]["areas"].values()[0]
```
Should become:
```
    entity = list(self.hass.data[const.DOMAIN]["areas"].values())[0]
```

I did not test this myself since someone else made the fix and notified me.
Now I didn't copy his work correcly and the error is still there 😟 

I am afraid I need to make a v1.5.2 already..

**Comment by tremebundo** [comment] 2021-01-29 21:06
I have just modified mqtt.py that way and I can confirm that change works.
Thanks for your interest and quick support.

**Comment by nielsfaber** [comment] 2021-01-30 09:11
https://github.com/nielsfaber/alarmo/commit/a5f2042310f94647e8540977f4b41329eac5c1ec should fix it (finally)

**Comment by nielsfaber** [comment] 2021-01-31 15:47
v1.5.2 is now released. I will close this issue since the problem is taken care of (and tested to be working).

**Closed by nielsfaber** 2021-01-31 15:47 UTC
Labels: bug, work-in-progress
