### ISSUE TITLE
Actionable Notifications - Force Arm not working

### ISSUE THREAD

**Issue by onkytonk** [nielsfaber/alarmo#60] opened 2020-12-13 10:21 UTC
I have implemented actionable notifications on ios. 

The options come up perfectly fine when I there is an open sensor, however, when I try to "Force Arm" the exit delay begins again, but then it still fails to arm. This is an endless loop, and I'm never able to force arm the system. 

Not sure what I'm missing, or if its a bug. 

I have added the yaml into the config, and I have added the extra yaml to the notification under "service_data".

**Comment by nielsfaber** [comment] 2020-12-15 16:21
Could you share the config of your action (YAML) and in the configuration.yaml (if you use iOS)?
Also, can you share the HA log entries of this scenario?

**Comment by onkytonk** [comment] 2020-12-15 21:40
I have other actionable notifications working, so quite certain the other configs are correct. 

I can't seem to see anything related in my log. Perhaps I haven't got the correct log turned on in my config.

This is in my ios.yaml:

```
push:
  categories:
    - name: Alarm Arm Failure
      identifier: alarmo_arm_failure
      actions:
        - identifier: ALARMO_RETRY_ARM
          title: Retry Arm # feel free to change this text
          destructive: true
        - identifier: ALARMO_FORCE_ARM
          title: Force Arm # feel free to change this text
          destructive: true
```

**Comment by nielsfaber** [comment] 2020-12-22 17:24
I managed to reproduce this situation now as well.
Will work on a fix for it.

**Comment by nielsfaber** [comment] 2020-12-23 11:34
I released v1.4.1 which improves the forced arming.
Please test it and check whether the issue still persists.

**Comment by nielsfaber** [comment] 2021-01-03 15:11
I'm closing this issue, assuming this works now.
Let me know if you still experience problems..

**Closed by nielsfaber** 2021-01-03 15:11 UTC
Labels: bug, work-in-progress

**Comment by joshnorton** [comment] 2021-04-10 09:38
Hi, I have the same problem on Android with version 1.5.6. My "Failed to arm" notification is defined like so:

name: Failed to arm notification
modes: []
triggers:
  - event: arm_failure
actions:
  - service: notify.mobile_app_josh
    service_data:
      message: >-
        The alarm cannot be activated due to:
        {{open_sensors}}.
      title: Alarm activation failed
      data:
        actions:
          - action: ALARMO_RETRY_ARM
            title: Retry Arm
          - action: ALARMO_FORCE_ARM
            title: Force Arm
        ttl: 0
        sticky: 'true'
        color: '#FFA500'
        channel: home_alarm_activation_failed
        importance: high
        vibrationPattern: '100, 1000, 100, 1000, 100'

Also, I have just seen your custom alarm panel (which is awesome). A feature request would be to have the "Force Arm" function available there as well.
