### ISSUE TITLE
Unifi Smart Detections missing from Sensor list?

### ISSUE THREAD

**Issue by matt-terry** [nielsfaber/alarmo#564] opened 2022-09-01 15:53 UTC
### Alarmo Version

v1.9.5

### HA Version

2022.8.7

### Bug description

Trying to add 'person detected' sensor from my Unifi G4 Bullet camera. The entity exists in HA as a 'switch': 
`switch.house_front_detections_person`

But this is not listed in the Alarmo sensor list, I presume switch types are filtered out? Is there anyway to get this added as a sensor as I really want a person detected sensor as opposed to motion detected sensor (pets/animals triggering incorrectly).

Thanks

**Comment by nielsfaber** [comment] 2022-09-01 16:51
A switch is not a sensor, but an actuator which you can set (on/off) yourself.
Alarmo only supports binary sensors.
You can create a binary sensor from the switch state using a template.
Closing because this is not a bug report.

**Closed by nielsfaber** 2022-09-01 16:51 UTC
Labels: bug

**Comment by matt-terry** [comment] 2022-09-02 06:16
My apologies, switch was the wrong entity as you say, that just enables or disables person detections. 

As per the UniFi integration page, https://www.home-assistant.io/integrations/unifiprotect/, the correct entity is sensor.house_front_detected_object that can report back either none, person, or vehicle. Is there anyway to incorporate this in Alarmo?

Thanks

**Comment by matt-terry** [comment] 2022-09-02 14:52
FYI this YAML code works as an automation trigger:

platform: state
entity_id: sensor.camera_name_detected_object
to: person

If this isn't natively supported in Alarmo (if not it should be a FR), then I will look into how this can be converted into a binary sensor output so its readable.

Thanks

**Comment by nielsfaber** [comment] 2022-09-02 16:50
I don’t want to include integration-specific aspects into Alarmo. In this particular case, the sensor state going to 'person' on detection (rather than on/off) is such thing.
Here’s a code example for creating a binary sensor from it:
```
template:
  - binary_sensor:
      - name: Unify motion detected 
        device_class: motion
        state: >
          {{ is_state("sensor.my_unifi_sensor", "above_person") }}
```
You can place this in the configuration.yaml (or similar).

**Comment by matt-terry** [comment] 2022-09-02 17:09
Keeping it device agnostic makes complete sense. Thanks for the code, I'll give that a try!

**Comment by emcniece** [comment] 2022-10-25 02:53
I had great luck with this, thank you.
