### ISSUE TITLE
Prevent re-executing of actions for initial alarm state after restarting HA

### ISSUE THREAD

**Issue by tteck** [nielsfaber/alarmo#33] opened 2020-11-24 15:38 UTC
Logger: homeassistant.components.alarm_control_panel
Source: core.py:1401
Integration: Alarm control panel (documentation, issues)
First occurred: 10:35:51 AM (2 occurrences)
Last logged: 10:35:51 AM

Error adding entities for domain alarm_control_panel with platform alarmo
Error while setting up alarmo platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 356, in async_added_to_hass
    await self.async_update_state(STATE_ALARM_DISARMED)
  File "/config/custom_components/alarmo/alarm_control_panel.py", line 393, in async_update_state
    await self.automations.async_handle_state_update(state=state, last_state=last_state)
  File "/config/custom_components/alarmo/automations.py", line 71, in async_handle_state_update
    await self.async_execute_automation(automation_id)
  File "/config/custom_components/alarmo/automations.py", line 117, in async_execute_automation
    await async_call_from_config(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 97, in async_call_from_config
    await hass.services.async_call(*parms, blocking, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1401, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service notify/alexa_media

**Comment by tteck** [comment] 2020-11-24 15:41
It may be because of my Alexa notifications?

`name: Armed Home Echo Dot
modes:
  - armed_home
triggers:
  - state: armed
actions:
  - service: notify.alexa_media
    service_data:
      data:
        type: tts
      message: 'The security system is now ARMED, in home mode.'
      target:
        - media_player.tommy_s_echo_dot
`

**Comment by nielsfaber** [comment] 2020-11-24 15:47
Last line says it all:
`Unable to find service notify/alexa_media`
Service was not found in HA.

I cannot really help that.

The only thing i can imagine, is that after startup the devices in your config are started one by one, maybe Alarmo is just too quick..

**Comment by tteck** [comment] 2020-11-24 16:21
You are correct. I disabled all notifications that included notify.alexa_media and reboot went normal.
I had those automations in NodeRed and everyhing was good. I wanted to keep everything alarm related in Alarmo. ;)

**Comment by nielsfaber** [comment] 2020-11-24 17:06
I think i should fix this behaviour.
Either prevent the (re-) execution of automations after restarting HA, or make sure Alarmo waits until HA is fully started.

**Comment by tteck** [comment] 2020-11-24 17:11
Preventing the (re-) execution of automations after restarting HA, that sounds best.

Thank you for your hard work!

**Comment by nielsfaber** [comment] 2020-11-30 16:48
Updating to v1.3.2 should solve the problem and prevents the automations from repeating when your restart HA.
Please close the issue if the problem is resolved.

**Closed** 2020-11-30 17:18 UTC
Labels: bug, work-in-progress
