### ISSUE TITLE
Manage rfid tags directly in Alarmo (or using a RFID tag to disarm alarm without code)

### ISSUE THREAD

**Issue by waazdakka** [nielsfaber/alarmo#386] opened 2022-02-07 11:00 UTC
### Checklist
- [ X ] I checked for similar existing requests (both open and closed) before posting.
- [ X ] My request is generic, other users may benefit from it too.

### Proposal
I created an automation to use my RFID tag's scanner with Alarmo. But since Alarmo's deactivation require to enter a code, I have to put plain code directly in the automation.
This brings 2 issues:
- I need to create a user "tag scanner" and put the code directly in the automation, which doesn't allow me to know who scanned the tag
- If I want to know who badged I practicaly need 1 automation per user (or a very complex one) since each user has his own code (that I'm not going to ask... bcause it's personnal 😅)

Could it be possible to integrate a tag management in Alarmo ?
Or maybe find a way to use the Alarmo's disarm service without a code (which seems to be opposite to the alarm's operation) ?

### Additional info
Create a menu allowing to add registered tags (You should have registered them before in HA), exactly like adding sensors but in the "Code" menu

**Comment by nielsfaber** [comment] 2022-02-07 18:52
Duplicate of https://github.com/nielsfaber/alarmo/issues/146

**Closed by nielsfaber** 2022-02-07 18:52 UTC
Labels: feature_request

**Comment by nielsfaber** [comment] 2022-02-07 18:53
> Or maybe find a way to use the Alarmo's disarm service without a code (which seems to be opposite to the alarm's operation) ?

I think this is the direction I want to go, because I cannot keep up with the requests for automation features 😅
