### ISSUE TITLE
adding rfid tags

### ISSUE THREAD

**Issue by pvtex** [nielsfaber/alarmo#951] opened 2024-05-27 21:20 UTC
i think including rfid tags would be great.
i am using a wiegand keypad with rfid reader with a esp8266 with esphome.
now i have a bunch of automations to get the tags over ha and pincode from alarmo working together.

i need to input pin code and then scan the rfid card to open my door locks.
the keypad writes the pincode to an input_text helper and when a known rfid card is scanned this pincode and the arm/disarm command is send to alarmo via an automation in ha.

there is a tag_scanned event in ha, so this could be used and a new field in the codes section for the rfid tag id would be needed.
if there will be an option to choose between code or rfid only or both needed that would be perfect.

**Comment by nielsfaber** [comment] 2024-06-02 18:04
Duplicate of #146

**Closed by nielsfaber** 2024-06-02 18:04 UTC
Labels: feature_request
