### ISSUE TITLE
Extend entry delay

### ISSUE THREAD

**Issue by ClearlyDazed** [nielsfaber/alarmo#763] opened 2023-07-08 22:33 UTC
Would like to see an option to extend the entry delay for a device or group. On entry to the garage it can take longer than 180 seconds to get to the panel and disarm the alarm.

**Comment by nielsfaber** [comment] 2023-07-09 06:41
Duplicate of https://github.com/nielsfaber/alarmo/issues/709

**Closed by nielsfaber** 2023-07-09 06:41 UTC
Labels: feature_request
