### ISSUE TITLE
code for silent alarm

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo#531] opened 2022-07-24 15:03 UTC
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
code option: activate silent alarm (e.g. call police, neighbors etc)

### Additional info
of course this is absolutely out of a movie :D but lets assume someone is forcing you to disarm the alarm. a special code for disarming the alarm/sirens while triggering a silent-alarm (sms/call) at the same time would be awesome :D

**Comment by nielsfaber** [comment] 2022-07-24 20:56
Duplicate of https://github.com/nielsfaber/alarmo/issues/248.

**Closed by nielsfaber** 2022-07-24 20:56 UTC
Labels: feature_request
