### ISSUE TITLE
Exclude by Arm_Home

### ISSUE THREAD

**Issue by audenbuch** [nielsfaber/alarmo#57] opened 2020-12-11 05:27 UTC
Hello, excellent project, thank you very much for the contribution.

It is possible to include a condition, when you are arming at home to be able to exclude some groups of sensors, such as windows that you want to keep open at night while at home.

I have tried to select the Allow open option, but after fulfilling the trigger the alarm is activated.

**Comment by nielsfaber** [comment] 2020-12-14 16:36
This is a fair request, I am planning to improve functionality that allows this.

What I would like to accomplish is that you could mark a sensor as "optional", and in this case it would be automatically bypassed/excluded if it is open when you arm.

The problem is that some users would allow a window to be bypassed at night, but certainly not when leaving the house.
I'm not sure how to provide an option that would give such flexibility.

**Comment by nielsfaber** [comment] 2020-12-15 16:52
I thought about this some more, I think it is better not to add such function.
My main concern:
What if you left a window open, but this was not intended (i.e. you forgot to close it)?
Marking it as optional, would mean it would automatically be bypasssed and the window would not be protected.
I think it's best to inform the user of the open window, and ask him/her (every time) if the sensor should be bypassed or it was forgotten.

**Closed** 2021-01-25 17:00 UTC
Labels: enhancement
