### ISSUE TITLE
Error when loading interface 

### ISSUE THREAD

**Issue by ddanielww** [nielsfaber/alarmo#810] opened 2023-10-16 20:43 UTC
### Alarmo Version

V1.9.10

### HA Version

Lastest

### Bug description

When loading the alarmo GUI it shows loading, but never loads.

### Steps to reproduce

When loading the alarmo GUI it shows loading, but never loads.

Fresh install with latest ha and alarmo.

**Comment by nielsfaber** [comment] 2023-10-17 12:09
Duplicate of #807

**Closed by nielsfaber** 2023-10-17 12:09 UTC
Labels: bug
