### ISSUE TITLE
[Feature Request] - Allow to set Channel and Priority for Notifications

### ISSUE THREAD

**Issue by seanmccabe** [nielsfaber/alarmo#174] opened 2021-04-05 07:42 UTC
Would be awesome if we could set the Channel and Priority for Notifications.

I have a variety of channels some of which are just general, or environmental so not really a priority and do not get past my do not disturb. But things like motion detected on my security cameras come through as High priority on the "Security" channel, as such, bypassing Do not disturb and allowing me to set a specific notification sound as well.

**Comment by nielsfaber** [comment] 2021-04-07 04:06
Duplicate of https://github.com/nielsfaber/alarmo/issues/168

**Closed by nielsfaber** 2021-04-07 04:06 UTC
