### ISSUE TITLE
blank Actions when you want to re-edit

### ISSUE THREAD

**Issue by tarbax** [nielsfaber/alarmo#374] opened 2022-01-16 14:09 UTC
### Alarmo Version

v1.8.2

### HA Version

2021.12.9

### Bug description

after creating an action i can't re-edit them cause i get a blank screen
notifications do work when i try to re edit them

**Comment by nielsfaber** [comment] 2022-01-16 14:11
Duplicate of #369, #372, #373

**Closed by nielsfaber** 2022-01-16 14:11 UTC
Labels: bug
