### ISSUE TITLE
alarmo 1.8.7 new notification

### ISSUE THREAD

**Issue by morenonew2** [nielsfaber/alarmo#425] opened 2022-03-21 14:22 UTC
### Alarmo Version

1.8.7

### HA Version

2022.3.5

### Bug description

new notification window pop up doesnt work. dont open. when I simple click on new notification (action tab)

thanks

**Comment by nielsfaber** [comment] 2022-04-01 19:03
There is no pop up window for creating notifications. I don't understand the issue.
Please share a screenshot/video/etc.

**Comment by axerontios** [comment] 2022-04-03 18:50
I have the same issue on the latest hass version as we speak. Fresh installation of alarm. On the action TAB i click 'new notification' and nothing happens. I cleaned cookies just in case and tried mozzila and chrome as well. 

I saw the errors below in developer in chrome while i clicked the new notification button. Not sure if that helps.

An SSL certificate error occurred when fetching the script.
home-assistant.ts:32 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://192.168.x.xxx:8123/') with script ('https://192.168.x.xxx:8123/service_worker.js'): An SSL certificate error occurred when fetching the script.
(anonymous) @ home-assistant.ts:32
await in (anonymous) (async)
(anonymous) @ home-assistant.ts:32
setTimeout (async)
value @ home-assistant.ts:32
_$AE @ styles.ts:368
performUpdate @ styles.ts:368
scheduleUpdate @ styles.ts:368
_$EC @ styles.ts:368
await in _$EC (async)
requestUpdate @ styles.ts:368
o @ styles.ts:368
b @ styles.ts:368
w @ styles.ts:368
F @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
(anonymous) @ styles.ts:368
me @ styles.ts:368
(anonymous) @ home-assistant.ts:32
s @ home-assistant-main.ts:41
E @ typography.js:181
t @ typography.js:181
window.CustomElementRegistry.define @ typography.js:181
finisher @ styles.ts:368
runClassFinishers @ home-assistant-main.ts:41
(anonymous) @ home-assistant-main.ts:41
(anonymous) @ home-assistant-main.ts:41
(anonymous) @ home-assistant.ts:32
(anonymous) @ home-assistant.ts:32
30alarmo:2319 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at qs (alarmo:2319:4356)
    at Xs.render (alarmo:2474:46)
    at Xs.update (alarmo:37:582)
    at Xs.performUpdate (alarmo:25:4734)
    at Xs.Πq (alarmo:25:4350)
    
    Thanks for the great work done in this. If i got this one sorted i will be able to give it a go.

**Comment by nielsfaber** [comment] 2022-04-03 19:07
@axerontios Thanks for reporting this.
The error points to the function [getNotifyServices](https://github.com/nielsfaber/alarmo/blob/main/custom_components/alarmo/frontend/src/data/actions.ts#L214-L223) which makes a list based on all `notify` and `tts` services registered in HA.
Could you check in Developer Tools -> Services if you have such services? Maybe the code is not able to handle the situation where a user doesn't have any registered.

**Comment by axerontios** [comment] 2022-04-03 20:03
I do have a bunch of notify services.. Like for my android tv

**Comment by morenonew2** [comment] 2022-04-04 08:46
i solved my issue. only add to configuration.yaml this lines if you dont have. 

# Example configuration.yaml entry for Google TTS service
tts:
  - platform: google_translate

and all go like a charm.

**Comment by nielsfaber** [comment] 2022-04-05 02:07
@axerontios Can you confirm you have no tts services in developer tools?
This might be the reason of this error. I didn't test for this condition.

**Comment by esackbauer** [comment] 2022-04-18 16:53
@nielsfaber I had the same problem, Getting blank frame when either trying to change an existing notification or create a new one.
I am not using tts in my installation, so I gave it a shot and tried. After I activated the tts settings to google-translate in the configuration.yaml I could edit the notifications.
After I disabled the tts integration again, the frames are empty again.

**Comment by drytoastman** [comment] 2022-04-22 20:36
I can confirm an error:  TypeError: can't convert undefined to object

https://github.com/nielsfaber/alarmo/blob/879ea52b7bb3a24e6666c9e4bb1aba55cf0f8dfe/custom_components/alarmo/frontend/src/data/actions.ts#L218

hass.services.tts returns undefined and Object.keys doesn't like it

**Comment by maximoei** [comment] 2022-05-01 10:23
Can confirm above as well, having no tts registered breaks the new notification screen

**Comment by nielsfaber** [comment] 2022-05-03 04:41
There is (finally) a fix on its way: https://github.com/nielsfaber/alarmo/commit/5c40a3d74c363fcf5c056856fd12b6e511b32c16
I will update you when a release is available.

**Comment by nielsfaber** [comment] 2022-05-05 18:17
This should be fixed by updating to v1.9.0.
Let me know if you still experience this problem after updating.

**Closed by nielsfaber** 2022-05-05 18:17 UTC
Labels: bug, work-in-progress
