### ISSUE TITLE
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9

### ISSUE THREAD

**Issue by bernardesarthur** [nielsfaber/alarmo#1024] opened 2024-09-04 17:37 UTC
### Checklist

- [X] I am using the latest version of Alarmo (latest version can be found [here](https://github.com/nielsfaber/alarmo/releases/latest))
- [X] I checked for similar existing requests (both open and closed) before posting.

### Alarmo Version

v1.10.4

### HA Version

2024.9.0

### Bug description

```
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues`
`Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
```

### Steps to reproduce

Just execute Alarmo with Home Assistant Core 2024.9.0

### Relevant log output

```shell
`Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues`
`Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues`
```

**Comment by Awebian** [comment] 2024-09-05 04:19
Same message / issue after upgrading to 2024.9

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 9:13:56 PM (2 occurrences)
Last logged: 9:13:56 PM

Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 97: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
Detected that custom integration 'alarmo' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/alarmo/alarm_control_panel.py, line 102: platform.async_register_entity_service(, please create a bug report at https://github.com/nielsfaber/alarmo/issues
```

**Comment by nielsfaber** [comment] 2024-09-08 06:23
Duplicate of #1020

**Closed by nielsfaber** 2024-09-08 06:23 UTC
Labels: bug
