### ISSUE TITLE
TypeError: e.triggers is undefined

### ISSUE THREAD

**Issue by rossbcan** [nielsfaber/alarmo#182] opened 2021-04-20 15:02 UTC
Just installed alarmo;

HA log filled with:
[frontend.js.latest.202104073] https://hassio.rossco.dynu.com/api/panel_custom/alarmo:1806:3097 TypeError: e.triggers is undefined

Suggestions?

![image](https://user-images.githubusercontent.com/13289915/115418857-d6d85e00-a1c7-11eb-9870-259a32cd1e78.png)

**Comment by nielsfaber** [comment] 2021-04-22 10:22
Thanks for reporting this, i will check it out.

**Comment by nielsfaber** [comment] 2021-04-25 05:47
I made some small changes that should suppress the errors in the logs: https://github.com/nielsfaber/alarmo/commit/9d0efa07adfdb5350f6dda57e61ea0c177bac81c

The error however seems to be caused by an notification which is wrongly configured.
Did you use the YAML editor to customize some notifications?
Could it be that the `triggers` section was removed?

**Comment by rossbcan** [comment] 2021-04-25 13:56
Have not seen this error since initial install. Possibly due no notifications or triggers configured at that point. No using yaml for either.

**Comment by nielsfaber** [comment] 2021-06-01 19:22
Closing, assumed fixed.

**Closed by nielsfaber** 2021-06-01 19:22 UTC
Labels: bug, work-in-progress
