### ISSUE TITLE
ALARMO integration does not appear after installing through HACS and restarting (2022.7.3)

### ISSUE THREAD

**Issue by juancameijeiras** [nielsfaber/alarmo#520] opened 2022-07-16 06:45 UTC
### Alarmo Version

v1.9.4

### HA Version

2022.7.3

### Bug description

ALARMO integration does not appear after installing through HACS and restarting, I am using a RPI4

### Steps to reproduce

Install through HACS, restart HA and check for the integration, it does not appear. Restart once again and check again, not available. Uninstall ALARMO through HACS, restart then install again and check in configuration-integrations, still does not appear. I can see the component has been downloaded in the custom components folder. I then proceeded to update HA to version 2022.7.5 as I was running 2022.7.3, then it appeared.

**Comment by nielsfaber** [comment] 2022-07-16 06:53
Duplicate of https://github.com/nielsfaber/alarmo/issues/387

**Closed by nielsfaber** 2022-07-16 06:53 UTC
Labels: bug
