### ISSUE TITLE
Monitoring via SIA DC-09

### ISSUE THREAD

**Issue by skaggerik** [nielsfaber/alarmo#924] opened 2024-04-15 22:21 UTC
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
The ability to connect alarmo to a monitoring service would be nice. Perhaps the addition would be easy for someone with some more understanding of python, and UDP/TCP? The standard for SIA DC-09 allows for image verification in the events, which could be combined with homeassistant. 

Should pulling be enabled, this would also function as an uptime monitor for home assistant. 

### Additional info

SIA DC-09 Standard: https://www.securityindustry.org/wp-content/uploads/2017/10/dc09_r2021_20201027.pdf

Project for sending events: https://github.com/jvanovost/dc09_spt

Example of report: "CB640375″ADM-CID”0086L0#1234[#1234\|1130 02 001][Vhttps://ajax-sample.com/first_photo.jpg,https://ajax-sample.com/second_photo.jpg]_16:43:06,10-07-2020" 

Note how the image is just uploaded to a server, with the address in clear text.

**Comment by nielsfaber** [comment] 2024-05-08 12:02
Duplicate of https://github.com/nielsfaber/alarmo/issues/686

**Closed by nielsfaber** 2024-05-08 12:02 UTC
Labels: feature_request
