### ISSUE TITLE
Exit delay + Entry delay + open sensor disarming

### ISSUE THREAD

**Issue by thecheekymonkey** [nielsfaber/alarmo#583] opened 2022-09-27 11:04 UTC
request for 

1. Exit delay audible notification (buzzer) until alarmo armed.
2. Entry delay audible notification (buzzer) until alarmo disarmed.
3. Open sensor disarming and buzzer silence.

Ive managed to create these using some scripts and also alarmo's actions but its quite frustrating to create. I have to created 2 scripts

script one is exit delay buzzer. toggles my siren on and off every 200ms until alarmo is armed.
script two is entry delay buzzer, this toggles my siren on and off every 100ms until alarmo is disarmed.

i then use alarmo action to call these when alarmo is set to arming (exit delay script) or pending (entry delay script)
these work great as long as you dont exceed 30 seconds entry delay, going anywhere over this figure results in the sire triggering constantly once entry delay has completed and alarmed should be armed.

open sensor disarm is so that if i set my alarm and say my front door is open and stays open whilst exit delay completes, alarm should count down exit delay and then not arm and siren should not sound.  as it is, on completion of exit delay , alarm remains disarmed but siren triggers and i am unable to disable it by entering code or running any script. i have to restart home assistant and restart my alarm interface hardware.

id like to thank you for your integration, its great and is much appreciated.

im just trying to create similar behavior to a real alarm.

audible notifications i think are needed on exit and entry, especially entry so you know the alarm is set. home assistant is brilliant but ive spent days and days trying to get progress on this, but there are a million ways to do the same thing and inevitably something breaks at some point or another. many thanks

**Comment by nielsfaber** [comment] 2022-09-27 15:47
Duplicate of #582

**Comment by nielsfaber** [comment] 2022-09-27 15:48
Please add your input in the other request, they seem to describe more or less the same.

**Closed by nielsfaber** 2022-09-27 15:47 UTC
Labels: feature_request
