### ISSUE TITLE
core-2021.5.0b1 compatibility

### ISSUE THREAD

**Issue by thundergreen** [nielsfaber/alarmo#191] opened 2021-04-29 08:23 UTC
Hey there,

thanks for this awesome app.. Is it possible to upgrade this app for latest beta of Home-Assstant.It throws error:

```
Logger: homeassistant.config_entries
Source: custom_components/alarmo/card.py:37
Integration: Alarmo (documentation, issues)
First occurred: 10:16:41 AM (1 occurrences)
Last logged: 10:16:41 AM

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'
```

Thanks :)

**Comment by Repsionu** [comment] 2021-04-29 09:25
Same here, Alarmo generated 2 entries in Integrations both wih red exclamation mark and message: Failed to set up. One device says integration alarmo, another **alarmo,alarmo** :-) Sorry I deleted the log and waiting for db repack to finish before restart. Also Alarmo UI keynoard panel said unavailable (no custom component) - deleted and readded- now OK :-)
Best and will provide more precise data after HA reboot.

**Comment by nielsfaber** [comment] 2021-04-29 09:51
Duplicate of #186

**Closed by nielsfaber** 2021-04-29 09:51 UTC
