### ISSUE TITLE
Vacuum mode -  enable/disable sensors based on other sensor (or way to enable/disable sensors)

### ISSUE THREAD

**Issue by diabl0** [nielsfaber/alarmo#508] opened 2022-06-26 13:53 UTC
I want to run an automatic vacuum cycle after leaving home and arming the alarm, but my roborock is triggering motion sensors causing alarms. I can detect when the vacuum is running, but can't find a way to disable/enable motion sensors in this time

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposals

- Service call allowing to disable/enable particular sensor (or sensor type)
- Ability to enable/disable sensors based on another sensor state (this way we can configure it via UI)

### Additional info

With service call, we can easily write automation to disable/enable particular sensors whenever we need to. Probably easier to implement but harder for users to setup.

With sensor overide in Alarmo panel sensor advanced settings we may select other binary sensor indicating that this sensor should be enabled or not. May be harder to implement, but it will give users the ability to set up this from UI.

**Comment by LucaBors** [comment] 2022-06-28 03:07
Yes, this can be really useful!

**Comment by nielsfaber** [comment] 2022-06-28 05:40
Duplicate of https://github.com/nielsfaber/alarmo/issues/289

**Closed by nielsfaber** 2022-06-28 05:40 UTC
Labels: feature_request

**Comment by diabl0** [comment] 2022-07-23 07:36
Maybe it will be useful for others like me: 
as a "workaround" I'm using HTTP calls to disable/enable sensors as needed:



```
curl --location --request POST 'https://your.HA.IP/api/alarmo/sensors' \
--header 'Authorization: Bearer ---token---' \
--header 'Content-Type: application/json' \
--data-raw '{
    "entity_id": "binary_sensor.salon_motion_door_occupancy",
    "enabled": true
}'
```

Token to be generated in HA profile page. 

I'm using it in node-red to disable/enable Alarmo sensors based on other events (like in my case status of a vacuum cleaner) and it works fine for now.
