### ISSUE TITLE
Push iOS option is now deprecated by HA 2022.02.0

### ISSUE THREAD

**Issue by chemelli74** [nielsfaber/alarmo#382] opened 2022-02-02 23:15 UTC
### Alarmo Version

v1.8.3

### HA Version

2022.02.0

### Bug description

Using example for push configuration generates a log line:

`2022-02-02 23:28:26 WARNING (MainThread) [homeassistant.components.ios] The 'puh' option near /config/configuration.yaml:16 is deprecated, please remove it from your configuration`

### Steps to reproduce

- Upgrade to 2022.02.2
- Enable actionable notifications

**Comment by nielsfaber** [comment] 2022-02-08 05:49
This is an error caused by your `configuration.yaml` file, not by Alarmo. 
You will have to fix that yourself.

I updated the [documentation](https://github.com/nielsfaber/alarmo#actionable-notifications) according to the changes in HA, you may need to update your existing notifications to make them work again.
In v1.8.4 some changes are made as well to correctly handle the button actions.

Hope that solves your issue, please close it if so.
Otherwise, let me know.

**Comment by chemelli74** [comment] 2022-02-09 08:17
> This is an error caused by your `configuration.yaml` file, not by Alarmo. You will have to fix that yourself.

True, but my cfg was based on your documentation ;-)
So it was worth reporting

Simone

**Closed** 2022-02-13 12:08 UTC
Labels: bug, work-in-progress
