### ISSUE TITLE
Unable to find requested entity

### ISSUE THREAD

**Issue by StanESmith** [nielsfaber/alarmo#357] opened 2021-12-19 14:03 UTC
### Alarmo Version

V1.8.1

### HA Version

2021.12.3

### Bug description

Home assistant reports unable to find requested entity alarm_control_panel.alarmo is already in use by alarm_control_panel.alarmo. This stops Any arm/disarm action from taking place. Only way to solve it is to roll back to core version 2021.12.2.

### Steps to reproduce

Upgrade core to 2021.12.3 and attempt to arm the alarm.

**Comment by nielsfaber** [comment] 2021-12-19 17:36
For me all looks and works OK in 2021.12.3:
![image](https://user-images.githubusercontent.com/16861605/146684808-be8ab0cc-b6e3-46b9-a1f5-52744006466b.png)

![image](https://user-images.githubusercontent.com/16861605/146684826-448ea20a-a231-4a5b-ac37-a7e56fcaed1b.png)

I don't think the issue is related to your HA version.

**Comment by StanESmith** [comment] 2021-12-20 02:16
Well, I'm not sure what the issue was related too. I restored from a backup of the core, let it run all day, and just now upgraded again to 2021.12.3 and Alarmo works fine. No errors in the log. I'll keep watching on this one. Not sure if it was a fluke.

**Comment by nielsfaber** [comment] 2021-12-24 10:21
I will close this for now because I'm missing proof so far that this is actually a bug in Alarmo.
Hope you agree, if this comes back let's re-open the case

**Closed by nielsfaber** 2021-12-24 10:21 UTC
Labels: bug

**Comment by StanESmith** [comment] 2021-12-24 21:11
Yeah that’s fine for now. Looks like it was a one off.
