### ISSUE TITLE
Changing state of master entity, home assistant stops responding

### ISSUE THREAD

**Issue by icex2** [nielsfaber/alarmo#920] opened 2024-04-05 10:00 UTC
### Alarmo Version

v1.9.15

### HA Version

2024.4

### Bug description

After updating the HA core to 2024.4, when I change the arm state of the alarmo master entity, HA immediately stops responding and becomes unaccessible via the UI (web and app). I have my alarm system broken up into several sub-alarm entities, e.g. windows, door, garage etc.
I can still change the arm state of the sub-alarm entities to arm (night, home) and disarm without any issues. 

HA becomes automatically available again after several minutes once the supervisor watchdog forced HA to restart.

I am running HA on Home Assistant OS 12.1. I can still connect to the machine by ssh.

Further things I tested without success:

* Power cycle the physical machine HA is running on
* Restart the integration
* Reconfigure the integration
* Remove the master alarm entity and add it again
* Remove and re-install the integration

For now, I rolled back my core HA installation to 2024.3.3. and alarmo is working again. Keeping this as a mitigation to have an operational HA setup.

### Steps to reproduce

* Updated HA core from 2024.3.3 to 2024.4
* Switch the arm state of the alarmo master entity to another state, e.g. from home to night
* HA UI becomes unresponsive

### Relevant log output

```shell
Once I switched the arm state on the master entity, the HA logs are flooded with the following until the instance is being forced restarted by the supervisor watchdog:


2024-04-05 10:31:39.436 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-04-05 10:31:39.436 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-04-05 10:31:39.436 ERROR (MainThread) [homeassistant] Error doing job: Task was destroyed but it is pending!
2024-04-05 10:31:40.324 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7fa171de7580>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5982' coro=<ControllerApplication.on_zdo_relays_message() running at /usr/local/lib/python3.12/site-packages/zigpy_znp/zigbee/application.py:498>> while another task <Task finished name='Task-4496' result=None> is being executed.
2024-04-05 10:31:40.371 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7fa171de7d30>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5983' coro=<ControllerApplication.on_af_message() running at /usr/local/lib/python3.12/site-packages/zigpy_znp/zigbee/application.py:548>> while another task <Task finished name='Task-4496' result=None> is being executed.
2024-04-05 10:31:40.439 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7fa169937700>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5984' coro=<BaseSelectorEventLoop._accept_connection2() running at /usr/local/lib/python3.12/asyncio/selector_events.py:213>> while another task <Task finished name='Task-4496' result=None> is being executed.
2024-04-05 10:31:40.440 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7fa169531a50>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5985' coro=<BaseSelectorEventLoop._accept_connection2() running at /usr/local/lib/python3.12/asyncio/selector_events.py:213>> while another task <Task finished name='Task-4496' result=None> is being executed.
2024-04-05 10:31:41.018 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback <_asyncio.TaskStepMethWrapper object at 0x7fa171de6aa0>()
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-5986' coro=<BaseSelectorEventLoop._accept_connection2() running at /usr/local/lib/python3.12/asyncio/selector_events.py:213>> while another task <Task finished name='Task-4496' result=None> is being executed.
```
```

**Comment by scoudibou** [comment] 2024-04-05 13:15
Hello,

Same problem for me.
I've tried to reinstall from scratch but same issue..

**Comment by russilker** [comment] 2024-04-05 15:23
Same problem here. Confirmed as soon as I try arming alarm, Home Assistant goes unreachable since I updated to 2024.4.

**Comment by nielsfaber** [comment] 2024-04-05 16:02
I am unable to reproduce this issue.
For me switching the master entity from armed home to armed away (and back) goes without problems. 
There are also no error messages in the logs for me.
I am using HA 2024.4 and use the alarmo-card to change modes from the UI.
At this point I am a bit clueless about the issue, especially given that the issue seems to be caused by the latest HA updates. From the changelog I cannot find any change that could explain the issue so it's not clear to me what should be adapted from within Alarmo to restore the compatibility.

**Comment by Wizzard72** [comment] 2024-04-05 17:08
I have the same problem. Aftershave arming or disarming home assistant crash.

**Comment by scoudibou** [comment] 2024-04-05 17:45
I've lost my logs at reboot but i've : 
2024-04-05 19:36:31.104 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-05 19:36:40.172 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alarmo' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alarmo/mqtt.py, line 49: self.hass.async_add_job(self._async_subscribe_topics()), please create a bug report at https://github.com/nielsfaber/alarmo/issues

**Comment by Wizzard72** [comment] 2024-04-05 17:55
I totally removed Alarmo. With 1 zone it works. I can switch it to armed away and armed hime. When I add a second zone and I switch the master zone home assistant crash

**Comment by Wizzard72** [comment] 2024-04-05 18:04
I have 2 zones. If I enable the alarm on the first zone it works, if I enable the second zone it crashes, if I use the master it ceashes

**Comment by fugazzy** [comment] 2024-04-05 18:10
I do experience the same issue: crash on switching the alarm state

**Comment by russilker** [comment] 2024-04-05 18:16
I found the issue, at least for me. It is caused by the NSPanel Blueprint, specifically having the alarmo alarm added as an entity there, enabling the NSPanel's alarm control panel page. Looks like an issue that has to do with how the NSPanel monitors the alarm state changes.

@icex2 @scoudibou @Wizzard72 Can you confirm if you use the NSPanel Blueprint, and if so, remove any references to your alarmo entities in the yaml of the NSPanel automation? Definitely check the yaml and not just the gui, I had leftover lines from old blueprint versions referencing my alarmo in my YAML that weren't visible in the interface. Or, just for testing, disable your NSPanel Blueprint automation entirely and see if the issue goes away.

**Comment by Wizzard72** [comment] 2024-04-05 18:32
I can conform that removing all the Alarmo entities from my nspanel blueprints solves this issue. 
Great that you find it, I would have never thought about the nspanels.

**Comment by scoudibou** [comment] 2024-04-05 18:41
I confirm that is linked to NSPanel Alarmo entity...

**Comment by fugazzy** [comment] 2024-04-05 20:39
> I do experience the same issue: crash on switching the alarm state. I have only one zone.

For me the problem was related to nspanel blueprint too.

**Comment by baloo2** [comment] 2024-04-05 20:46
Exactly the same problem. After update to 2024.4 I experienced number of crashed after arming/disarming Alarmo. After I removed Alarmo from NSPanel, everything works again. Thank you.

**Comment by russilker** [comment] 2024-04-05 21:25
I opened a bug on the [NSPanel Blueprint github](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2015) with this issue.

**Comment by russilker** [comment] 2024-04-06 06:54
> To which component you have the alarm entity associated to? Chips, custom buttons, button pages,...?
> 
> I'm trying to duplicate this issue.

I had it originally as "alarm:" in the YAML. I believe this is a legacy config from before 4.2, so I removed that and tried adding it as a home page custom button, same issue. Not sure about the other users in the thread I linked.

**Comment by baloo2** [comment] 2024-04-06 07:37
I had it in Custom buttons as well.

**Comment by fugazzy** [comment] 2024-04-06 07:42
I had it as custom button too.

**Comment by edwardtfn** [comment] 2024-04-06 10:21
Ok. I could duplicate the issue.
I will investigate it more and try to come with a solution.

**Comment by GravitySandwichh** [comment] 2024-04-06 12:40
I am running into this issue aswell without using anything related to the NSPanel for alarmo.

**Comment by edwardtfn** [comment] 2024-04-06 21:59
I see that Alarmo takes a huge amount of CPU when disarming. The NSPANEL Blueprint can take some CPU when an entity have any change. Looks like the combination of those are driving to a crash. It probably could happen if you are using only Alarmo and no NSPanel.
O have a quite powerful system and Alarmo disarming alone takes around 80% of CPU. That is more than a Raspberry Pi would be able to handle.
I can work to find a way to reduce the NSPanel side (no promises here), but I have no intention to look on Alarmo side. I will leave this to Alarmo team. 😉

**Comment by overdrivesFR** [comment] 2024-04-07 11:12
Alarmo up to date.
ESPHome and NSpanel blueprint 4.2.6.
Enabling Alarmo from web app or Nspanel crash Home Assistant.
Deleting Alarmo from the Nspanel like other mentioned seems to "fix" it.

**Comment by edwardtfn** [comment] 2024-04-07 12:23
> Not sure if related, but it usually happens when disarming with a device (keypad/button) using the `alarm_control_panel.alarm_disarm` service

NSPanel calls this service directly from ESPHome, but only when the alarm is disarmed from the panel's side.

**Comment by edwardtfn** [comment] 2024-04-07 15:28
As I mentioned earlier, NSPanel isn't totally innocent here. It takes lots of CPU for some operations, which will add to the lots of CPU taken by other things.
We probably can improve the nspanel side to take a bit less when updating Alarmo's info, and maybe this is the bit need for your system survive to the huge CPU taken by other components.

**Comment by ejpenney** [comment] 2024-04-07 20:55
I'm seeing crashes as well, I just enabled asyncio debug logging so I don't know for sure (yet), but I highly suspect Alarmo involvement (and two or three other custom components I use), the crashes correlate with the alarm control panel changing state (intermittently).  I don't have NSPanel.

It's worth noting it doesn't happen 100% of the time because each non-thread-safe call destabilizes asyncio, and it will _eventually_ crash.  bdraco explains it briefly here: https://github.com/home-assistant/core/issues/114849#issuecomment-2040997042

I'll monitor logs, though that's quite the firehose to sift through.  If/when it destabilizes again hopefully I can provide more data.

**Comment by edwardtfn** [comment] 2024-04-08 15:44
There is a new patch for Home Assistant where they fixed some things related to performance.
Could someone please update Home Assistant to v2024.4.2 and let us know if this issue persists?

**Comment by russilker** [comment] 2024-04-08 16:08
Updated, the issue persists.

**Comment by bdraco** [comment] 2024-04-09 00:22
> There is a new patch for Home Assistant where they fixed some things related to performance. Could someone please update Home Assistant to v2024.4.2 and let us know if this issue persists?

This needs to be fixed in the integration as its not something that can be fixed in a Home Assistant update. The unsafe thread operation in the custom integation always been there, but because 2024.4.x is faster, its more likely to happen.

https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading

I've pointed out quite a few places where the code needs to be fix this week when people post the full trace, but without a full trace with asyncio debug enabled its hard to help here.

When you enable [asyncio in debug mode](https://docs.python.org/3/library/asyncio-dev.html#debug-mode), it will be able to detect some of these bad calls and maybe even block them.  You can use the profiler service to do that:
https://www.home-assistant.io/integrations/profiler/#service-profilerset_asyncio_debug

If you can't get far enough along you can also enable `debugpy:` in `configuration.yaml` instead (but its much slower)
https://www.home-assistant.io/integrations/debugpy/

**Comment by bdraco** [comment] 2024-04-09 00:54
```diff
diff --git a/custom_components/alarmo/alarm_control_panel.py b/custom_components/alarmo/alarm_control_panel.py
index 20f1f02..99bb8f0 100755
--- a/custom_components/alarmo/alarm_control_panel.py
+++ b/custom_components/alarmo/alarm_control_panel.py
@@ -3,7 +3,7 @@ import datetime
 import logging
 import functools
 import operator
-
+from abc import abstractmethod^M
 # from homeassistant.components.alarm_control_panel import DOMAIN as PLATFORM
 from homeassistant.core import (
     HomeAssistant,
@@ -268,6 +268,9 @@ class AlarmoBaseEntity(AlarmControlPanelEntity, RestoreEntity):
             return
         _LOGGER.debug("ready_to_arm_modes updated to {}".format(", ".join(value).replace("armed_","")))
         self._ready_to_arm_modes = value
+        # Have a setter that make async api calls is not ideal as it^M
+        # makes it very easy to make a mistake and call this from a thread^M
+        # which will not be thread safe.^M
         async_dispatcher_send(self.hass, "alarmo_state_updated", self.area_id, None, None)
         self.async_write_ha_state()
 
@@ -340,6 +343,16 @@ class AlarmoBaseEntity(AlarmControlPanelEntity, RestoreEntity):
             context_id=context_id
         )
 
+    @abstractmethod^M
+    @callback^M
+    def async_update_state(self, state: str = None) -> None:^M
+        """update the state or refresh state attributes"""^M
+^M
+    @abstractmethod^M
+    @callback^M
+    def async_trigger(self, skip_delay: bool = False, open_sensors: dict = None):^M
+        """Trigger the alarm."""^M
+^M
     async def async_alarm_disarm(self, **kwargs):
         """Send disarm command."""
         _LOGGER.debug("alarm_disarm")
@@ -374,7 +387,7 @@ class AlarmoBaseEntity(AlarmControlPanelEntity, RestoreEntity):
         else:
             self.open_sensors = None
             self.bypassed_sensors = None
-            await self.async_update_state(STATE_ALARM_DISARMED)
+            self.async_update_state(STATE_ALARM_DISARMED)^M
             if self.changed_by:
                 _LOGGER.info("Alarm '{}' is disarmed by {}.".format(self.name, self.changed_by))
             else:
@@ -494,7 +507,7 @@ class AlarmoBaseEntity(AlarmControlPanelEntity, RestoreEntity):
     async def async_alarm_trigger(self, code=None) -> None:
         """Send alarm trigger command."""
         _LOGGER.debug("async_alarm_trigger")
-        await self.async_trigger(skip_delay=True)
+        self.async_trigger(skip_delay=True)^M
 
     async def async_added_to_hass(self):
         """Connect to dispatcher listening for entity data notifications."""
@@ -571,17 +584,18 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
             if initial_state == STATE_ALARM_ARMING:
                 await self.async_arm(self.arm_mode)
             elif initial_state == STATE_ALARM_PENDING:
-                await self.async_trigger()
+                self.async_trigger()^M
             elif initial_state == STATE_ALARM_TRIGGERED:
-                await self.async_trigger(skip_delay=True)
+                self.async_trigger(skip_delay=True)^M
             else:
-                await self.async_update_state(initial_state)
+                self.async_update_state(initial_state)^M
         else:
-            await self.async_update_state(STATE_ALARM_DISARMED)
+            self.async_update_state(STATE_ALARM_DISARMED)^M
 
         self.async_write_ha_state()
 
-    async def async_update_state(self, state: str = None):
+    @callback # nothing is awaited here^M
+    def async_update_state(self, state: str = None):^M
         """update the state or refresh state attributes"""
 
         if state == self._state:
@@ -613,7 +627,7 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
         command = self._arm_mode.replace("armed", "arm")
 
         if self._state != self._revert_state and self._revert_state:
-            await self.async_update_state(self._revert_state)
+            self.async_update_state(self._revert_state)^M
         else:
             # when disarmed, only update the attributes
             if self._revert_state in const.ARM_MODES:
@@ -680,7 +694,7 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
                             const.ATTR_CONTEXT_ID: context_id
                         }
                     )
-                await self.async_update_state(arm_mode)
+                self.async_update_state(arm_mode)^M
                 return True
 
         else:  # normal arm event (from disarmed via arming)
@@ -713,7 +727,7 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
                 )
                 self.delay = exit_delay
                 self.open_sensors = None
-                await self.async_update_state(STATE_ALARM_ARMING)
+                self.async_update_state(STATE_ALARM_ARMING)^M
 
                 @callback
                 async def async_leave_timer_finished(now):
@@ -728,7 +742,11 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
                 self.async_set_timer(exit_delay, async_leave_timer_finished)
                 return True
 
-    async def async_trigger(self, skip_delay: bool = False, open_sensors: dict = None):
+    @callback^M
+    # While this should be an async callback function because nothing is being^M
+    # awaited, you might want to leave it as a coroutine since it appears to be^M
+    # called from other platforms like `sensor`. This is not ideal.^M
+    def async_trigger(self, skip_delay: bool = False, open_sensors: dict = None):^M
         """Trigger request. Will only be called the first time a sensor trips."""
 
         if self._state == STATE_ALARM_PENDING or skip_delay or not self._arm_mode:
@@ -758,7 +776,7 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
 
         if not entry_delay:
             # countdown finished or immediate trigger event
-            await self.async_update_state(STATE_ALARM_TRIGGERED)
+            self.async_update_state(STATE_ALARM_TRIGGERED)^M
 
             if trigger_time:
                 # there is a max. trigger time configured
@@ -770,7 +788,7 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
                     self._changed_by = None
                     if self._config[const.ATTR_DISARM_AFTER_TRIGGER] or not self.arm_mode:
                         self.bypassed_sensors = None
-                        await self.async_update_state(STATE_ALARM_DISARMED)
+                        self.async_update_state(STATE_ALARM_DISARMED)^M
                     else:
                         self.open_sensors = None
                         await self.async_arm(self.arm_mode, bypass_open_sensors=False, skip_delay=True)
@@ -788,18 +806,20 @@ class AlarmoAreaEntity(AlarmoBaseEntity):
         else:  # to pending state
             self.delay = entry_delay
 
-            await self.async_update_state(STATE_ALARM_PENDING)
+            self.async_update_state(STATE_ALARM_PENDING)^M
 
-            @callback
+            # Coroutines cannot be callback functions, remove @callback^M
             async def async_entry_timer_finished(now):
                 """Update state at a scheduled point in time."""
 
                 _LOGGER.debug("async_entry_timer_finished")
-                await self.async_trigger()
+                self.async_trigger()^M
 
             self.async_set_timer(entry_delay, async_entry_timer_finished)
             _LOGGER.info("Alarm will be triggered after {} seconds.".format(entry_delay))
 
+    @callback # probably not run from any hass internals but would be run in the^M
+    # executor since @callback is missing^M
     def async_set_timer(self, delay, cb_func):
         if self._timer:
             self._timer()
@@ -847,7 +867,7 @@ class AlarmoMasterEntity(AlarmoBaseEntity):
             coordinator = self.hass.data[const.DOMAIN]["coordinator"]
             self._config = coordinator.store.async_get_config()
 
-            await self.async_update_state()
+            self.async_update_state()^M
             self.async_write_ha_state()
 
         self.async_on_remove(
@@ -855,15 +875,15 @@ class AlarmoMasterEntity(AlarmoBaseEntity):
         )
         await async_update_config()
 
-        @callback
+        # Coroutines cannot be callback functions, remove @callback^M
         async def async_alarm_state_changed(area_id: str, old_state: str, new_state: str):
             if not area_id:
                 return
-            await self.async_update_state()
+            self.async_update_state()^M
 
         async_dispatcher_connect(self.hass, "alarmo_state_updated", async_alarm_state_changed)
 
-        @callback
+        # Coroutines cannot be callback functions, remove @callback^M
         async def async_handle_event(event: str, area_id: str, args: dict = {}):
             if not area_id or event not in [
                 const.EVENT_FAILED_TO_ARM,
@@ -901,7 +921,9 @@ class AlarmoMasterEntity(AlarmoBaseEntity):
             self._state = STATE_ALARM_DISARMED
         self.async_write_ha_state()
 
-    async def async_update_state(self, state: str = None):
+    @callback # Nothing is being awaited here, this should be a normal function^M
+    # decorated with @callback to indicate that it should be run in the event loop^M
+    def async_update_state(self, state: str = None):^M
         """update the state or refresh state attributes"""
 
         if state:
@@ -1061,7 +1083,7 @@ class AlarmoMasterEntity(AlarmoBaseEntity):
 
         for item in self.hass.data[const.DOMAIN]["areas"].values():
             if item.state != self._revert_state and self._revert_state:
-                await item.async_update_state(self._revert_state)
+                item.async_update_state(self._revert_state)^M
 
         self._revert_state = None
         async_dispatcher_send(
@@ -1077,8 +1099,12 @@ class AlarmoMasterEntity(AlarmoBaseEntity):
         )
         self.async_write_ha_state()
 
-    async def async_trigger(self, skip_delay: bool = False):
+    @callback^M
+    # While this should be an async callback function because nothing is being^M
+    # awaited, you might want to leave it as a coroutine since it appears to be^M
+    # called from other platforms. This is not ideal.    ^M
+    def async_trigger(self, skip_delay: bool = False):^M
         """handle triggering via service call"""
         for item in self.hass.data[const.DOMAIN]["areas"].values():
             if item.state != self._revert_state:
-                await item.async_trigger(skip_delay=skip_delay)
+                item.async_trigger(skip_delay=skip_delay)^M
diff --git a/custom_components/alarmo/automations.py b/custom_components/alarmo/automations.py
index 9f63138..1e5215e 100755
--- a/custom_components/alarmo/automations.py
+++ b/custom_components/alarmo/automations.py
@@ -79,6 +79,7 @@ class AutomationHandler:
         self._sensorTranslationLang = None
         self._alarmTranslationLang = None
 
+        @callback # If you want this to run in the event loop, it needs to be decorated with @callback^M
         def async_update_config():
             """automation config updated, reload the configuration."""
             self._config = self.hass.data[const.DOMAIN]["coordinator"].store.async_get_automations()
diff --git a/custom_components/alarmo/event.py b/custom_components/alarmo/event.py
index 4b2bfce..086ad82 100755
--- a/custom_components/alarmo/event.py
+++ b/custom_components/alarmo/event.py
@@ -20,9 +20,10 @@ class EventHandler:
 
     def __del__(self):
         """Class destructor."""
+        # This is no guarantee when this will run, its better to be explicit
         self._subscription()
 
-    @callback
+    # coroutines cannot be callback functions, remove the callback decorators
     async def async_handle_event(self, event: str, area_id: str, args: dict = {}):
         """handle event"""
 
@@ -63,4 +64,5 @@ class EventHandler:
                 data["mode"] = const.STATE_TO_ARM_MODE[data["arm_mode"]]
                 del data["arm_mode"]
 
-            self.hass.bus.fire("alarmo_command_success", data)
+            # Use async api from async
+            self.hass.bus.async_fire("alarmo_command_success", data)
diff --git a/custom_components/alarmo/mqtt.py b/custom_components/alarmo/mqtt.py
index 0310bce..e31588a 100755
--- a/custom_components/alarmo/mqtt.py
+++ b/custom_components/alarmo/mqtt.py
@@ -36,6 +36,8 @@ class MqttHandler:
         def update_config(_args=None):
             """mqtt config updated, reload the configuration."""
             old_config = self._config
+            # This is calling an async api but the function isn't decorated with @callback
+            # or prefixed with async_, so it's not clear if it's safe to call this function
             new_config = self.hass.data[const.DOMAIN]["coordinator"].store.async_get_config()
 
             if old_config and old_config[ATTR_MQTT] == new_config[ATTR_MQTT]:
@@ -46,6 +48,9 @@ class MqttHandler:
 
             if not old_config or old_config[ATTR_MQTT][CONF_COMMAND_TOPIC] != new_config[ATTR_MQTT][CONF_COMMAND_TOPIC]:
                 # re-subscribing is only needed if the command topic has changed
+                # async_add_job is not safe to call from another thread, if this function
+                # should be called in the event loop decorator it with @callback, otherwise
+                # use hass.add_job
                 self.hass.async_add_job(self._async_subscribe_topics())
 
             _LOGGER.debug("MQTT config was (re)loaded")
diff --git a/custom_components/alarmo/sensors.py b/custom_components/alarmo/sensors.py
index 75c5538..634156f 100755
--- a/custom_components/alarmo/sensors.py
+++ b/custom_components/alarmo/sensors.py
@@ -129,6 +129,13 @@ class SensorHandler:
         self._group_events = {}
         self._startup_complete = False
 
+        # This is running in the executor not async. It will only run in the event loop^M
+        # if you decorate it with @callback. Verify all calls inside of it should^M
+        # run in the event loop and if they don't, wrap them with hass.async_add_executor_job^M
+        # keep it without the decorator, and remove the async_ prefix than make sure all^M
+        # async calls are wrapped in hass.add_job and the function being called is either^M
+        # a coroutine or decorated with @callback^M
+        @callback^M
         def async_update_sensor_config():
             """sensor config updated, reload the configuration."""
             self._config = self.hass.data[const.DOMAIN]["coordinator"].store.async_get_sensors()
@@ -144,6 +151,10 @@ class SensorHandler:
         )
         async_update_sensor_config()
 
+        # This looks like its intended to flip a flag which is thread safe so it could^M
+        # be run in the event loop by decorating it with @callback. It would be^M
+        # better to use the start helper from `homeassistant.helpers.start` instead^M
+^M
         def handle_startup(_event):
             self._startup_complete = True
 
@@ -320,7 +331,7 @@ class SensorHandler:
         if sensor_config[ATTR_ALWAYS_ON]:
             # immediate trigger due to always on sensor
             _LOGGER.info("Alarm is triggered due to an always-on sensor: {}".format(entity))
-            await alarm_entity.async_trigger(
+            alarm_entity.async_trigger(^M
                 skip_delay=True,
                 open_sensors=open_sensors
             )
@@ -333,7 +344,7 @@ class SensorHandler:
         elif alarm_state in const.ARM_MODES:
             # standard alarm trigger
             _LOGGER.info("Alarm is triggered due to sensor: {}".format(entity))
-            await alarm_entity.async_trigger(
+            alarm_entity.async_trigger(^M
                 skip_delay=(not sensor_config[ATTR_USE_ENTRY_DELAY]),
                 open_sensors=open_sensors
             )
@@ -341,7 +352,7 @@ class SensorHandler:
         elif alarm_state == STATE_ALARM_PENDING:
             # immediate trigger while in pending state
             _LOGGER.info("Alarm is triggered due to sensor: {}".format(entity))
-            await alarm_entity.async_trigger(
+            alarm_entity.async_trigger(^M
                 skip_delay=True,
                 open_sensors=open_sensors
             )
```

Here are some of the issues I found in a cursory review

**Comment by nielsfaber** [comment] 2024-04-09 12:34
@bdraco Thanks a million for your extensive code review! I will go over them update the code.

@all For those who are looking for a temporary quick-fix (until I am able to release a patch) I noticed that replacing these lines:
https://github.com/nielsfaber/alarmo/blob/42f49c82adef8c47bc399827a1fb721360a6def3/custom_components/alarmo/alarm_control_panel.py#L271-L272

by:
```python
 # async_dispatcher_send(self.hass, "alarmo_state_updated", self.area_id, None, None) 
 # self.async_write_ha_state() 
```

In other words commenting out these lines, eliminates the crashes (at least it does for me).
It will not have any negative impact on functionality unless you are making use of the ready_to_arm_modes property.

**Comment by eddiebullman** [comment] 2024-04-09 13:53
will try short term fix

**Comment by JMoratelli** [comment] 2024-04-09 14:37
> @bdraco Thanks a million for your extensive code review! I will go over them and update the code accordingly.
> 
> @ALL For those who are looking for a temporary quick-fix (until I am able to release a patch) I noticed that replacing these lines:
> 
> https://github.com/nielsfaber/alarmo/blob/42f49c82adef8c47bc399827a1fb721360a6def3/custom_components/alarmo/alarm_control_panel.py#L271-L272
> 
> by:
> 
> ```python
>  # async_dispatcher_send(self.hass, "alarmo_state_updated", self.area_id, None, None) 
>  # self.async_write_ha_state() 
> ```
> 
> In other words commenting out these lines, eliminates the crashes (at least it does for me). It will not have any negative impact on functionality unless you are making use of the ready_to_arm_modes property.


Solved here, thanks!

**Comment by nielsfaber** [comment] 2024-04-11 20:00
I released v1.10.0 of alarmo which contains many fixes as proposed by @bdraco .
Please update to the new version, especially if you use HA 2024.4 combined with the master alarm (otherwise freezes may occur).
If you still experience stability issues after updating please let me know.

**Comment by iajames** [comment] 2024-04-11 21:49
Looking good for me now. Thanks for the rapid fix!! Especially as I’m away this weekend and need the alarm set…

**Comment by skaggerik** [comment] 2024-04-11 22:39
I had this issue, but only at times, and thought it was connected to my z-wave devices, I use Ring keypad. I still had issues after switching to JS UI. I thought it was connected to fast entry of the digits of the code? Time will tell.

**Comment by overdrivesFR** [comment] 2024-04-14 12:07
I updated HA by mistake friday, instant crash obviously, so I gave 1.10 a try.
Seems fine.

**Comment by icex2** [comment] 2024-04-14 13:17
Updated HA core to 2024.4.3 and Alarmo to v1.10.0 today. Tested by arming/disarming different modes repeatedly without experiencing crashes. Personally, I consider this issues resolved.

**Comment by stephenmetts** [comment] 2024-04-20 15:37
After upgrading to 2024.4.3 and v1.10.0 today, Alarmo does not respond when attempting to change to any state.  This was previously working before the HA upgrade.  Are there steps I've missed along the way or is this still an open issue?

**Closed** 2024-05-08 09:08 UTC
Labels: bug, work-in-progress
