### ISSUE TITLE
Arm mode "vacation"

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo#358] opened 2021-12-21 14:19 UTC
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Home Assistant added the mode "armed_vacation". 
It might be beneficial for some users to be able to use that mode in Alarmo too.

### Additional info
![alarm](https://user-images.githubusercontent.com/88980079/146944512-0fcbc863-d74f-4579-83bc-460cb2196f76.png)

**Comment by nielsfaber** [comment] 2021-12-22 17:08
>  I checked for similar existing requests (both open and closed) before posting.

Doubt it 😉 

Duplicate of https://github.com/nielsfaber/alarmo/issues/260

Anyway, I _personally_ would probably not use it, but if others see it useful I don't want to limit them.

The main issue I see currently is GUI-related. Adding a 5th arm mode simply doesn't fit currently, I have to work out a new format for it.

![image](https://user-images.githubusercontent.com/16861605/147129330-8668fd25-ca09-4337-8360-58b480cd95af.png)

![image](https://user-images.githubusercontent.com/16861605/147129531-d83c6eb9-6b06-419d-91a1-f445942ead24.png)

**Comment by Eyco1981** [comment] 2021-12-22 17:43
Dang it! I apologize! I wrote it on the train and was sure nothing was requested earlier. My phones autocorrection changed vacation to vaccination in the search box.
https://github.com/nielsfaber/alarmo/issues?q=is%3Aissue+vaccination
-.-
But as there is no vaccination mode in Alarmo - the World Health Organization would be happy about that.

**Comment by Eyco1981** [comment] 2021-12-22 17:54
For the UI problem...
Maybe it would be possible to place the settings for custom_bypass and vacation below each other when selecting Custom?
Same icons but both modes enableable there?

**Comment by nielsfaber** [comment] 2021-12-22 18:25
Vaccination program is not yet in scope for Alarmo, but I think an open-source alternative could become very popular these days  😄 

Anyway, I will puzzle a bit with the GUI, give it a couple of weeks.

**Comment by nielsfaber** [comment] 2022-01-15 14:17
This functionality is added in `v1.8.2`.
Please test it and close the issue if all works OK. 
Otherwise please let me know.

**Closed** 2022-01-15 16:27 UTC
Labels: feature_request, work-in-progress
