### ISSUE TITLE
Require Multiple Sensors to Trigger

### ISSUE THREAD

**Issue by Ctrl-oops** [nielsfaber/alarmo#279] opened 2021-08-25 01:27 UTC
The ability to require more than 1 sensor to be "tripped" before causing a triggered/pending event

### Proposal
Add an Option to set the amount of sensors that need to have been "tripped" within a timeframe before moving to a trigged event. This would be to avoid going into a trigged event if one sensor is misbehaving.

### Additional info
Most areas in my house are covered by multiple sensors but unfortunately some sensors I have are recently misbehaving and moving to "tripped" when there is no motion, don't know what is causing this on my end. but the ability to set variables on how many devices need to trip within a timeframe would help me solve this issue. (My Sensors are Tradfri Motion ZigBee if anybody has any prior experience with similar issues)

P.S. Thanks for the great add-on :)

**Comment by nielsfaber** [comment] 2021-08-25 05:16
Duplicate of https://github.com/nielsfaber/alarmo/issues/253

**Comment by nielsfaber** [comment] 2021-08-25 07:42
I am closing this issue, let’s please continue the discussion in the other issue for this subject.

**Closed by nielsfaber** 2021-08-25 07:42 UTC
Labels: feature_request
