### ISSUE TITLE
 Actionable Notifications - Force Arm not working on Android

### ISSUE THREAD

**Issue by joshnorton** [nielsfaber/alarmo#180] opened 2021-04-16 18:23 UTC
Hi, on Android with version 1.5.6 I am unable to force the alarm to activate if a window sensor is open. My "Failed to arm" notification is defined like so:

name: Failed to arm notification
modes: []
triggers:
  - event: arm_failure
actions:
  - service: notify.mobile_app_josh
    service_data:
      message: >-
        The alarm cannot be activated due to:
        {{open_sensors}}.
      title: Alarm activation failed
      data:
        actions:
          - action: ALARMO_RETRY_ARM
            title: Retry Arm
          - action: ALARMO_FORCE_ARM
            title: Force Arm
        ttl: 0
        sticky: 'true'
        color: '#FFA500'
        channel: home_alarm_activation_failed
        importance: high
        vibrationPattern: '100, 1000, 100, 1000, 100'

Also, I have just seen your custom alarm panel (which is awesome). A feature request would be to have the "Force Arm" function available there as well.

_Originally posted by @joshnorton in https://github.com/nielsfaber/alarmo/issues/60#issuecomment-817108488_

**Comment by nielsfaber** [comment] 2021-04-22 10:26
Do you see the buttons in your push notification?
Nothing happens if you press any of them?
Is your device Android or IOS?
Is anything useful printed in the HA logs?

If not, could you try with debug logging enabled and see if anything is printed in the logs?
You can do so by adding this to configuration.yaml and restart:
```
logger:
  default: warning
  logs:
    custom_components.alarmo: debug
```

**Comment by joshnorton** [comment] 2021-04-23 10:18
Hi Niels,

I have an Android device. I enabled the logging you suggested, restarted the server, opened a door, and tried to arm the alarm.

I have attached the relevant portion of the log file to this reply. It seems that the arm_mode returned from the alarm_entity on line 291 of __init__.py is invalid. I have the two alarm modes "Armed Home" and "Armed Away" enabled in Alarmo via the UI.

[ha-alarmio.log](https://github.com/nielsfaber/alarmo/files/6364507/ha-alarmio.log)
![image](https://user-images.githubusercontent.com/13478193/115857399-f375cf80-a42d-11eb-9c47-61be44963c94.png)

**Comment by nielsfaber** [comment] 2021-04-24 09:06
Thanks for this information.
The problem is pretty clear to me now, it has to do with a change I made in the last release.
I will work on a fix, I hope to be able to make a new release in about a week.

**Comment by joshnorton** [comment] 2021-04-27 11:32
That's good news, thank you for fixing it.

**Comment by nielsfaber** [comment] 2021-05-01 05:03
It should be fixed after updating to v1.5.7.

**Comment by serlehf** [comment] 2021-05-16 21:05
I have the same issue of force arm or retry arm not working on IOS. The buttons show but they do nothing :(

**Comment by joshnorton** [comment] 2021-05-19 18:21
Hi Niels, this looks to be fixed for me in the latest build. Thank you very much.

**Closed** 2021-05-31 06:27 UTC
Labels: bug, work-in-progress
