### ISSUE TITLE
[Feature request] - use switch/input_boolean to arm/disarm Areas

### ISSUE THREAD

**Issue by Masterz69** [nielsfaber/alarmo#153] opened 2021-03-04 07:46 UTC
My use case: main house and so-called Barn. 
Would be nice to arm/disarm Barn by just pressing button/switch in a house.

It can be a switch/input_boolean which toggle between Disarmed/Armed Home, and another to Arm Away.

Sure, it can be accomplished by automation(s).
If included in integration - will give little bit more comfort for users.

**Comment by luckypants123** [comment] 2021-03-11 18:05
I think the issue with this is that it solves a problem already solved by automations, with the side effect of bloating Alarmo.
Just my 2c.

**Comment by Masterz69** [comment] 2021-03-11 18:36
Sure, this is not an actual problem. Kind of integral solution - all-in-one, not dispersed between automation/add-on/etc. 
My best wishes anyway.

**Comment by nielsfaber** [comment] 2021-04-05 06:07
This request is a (approximate) duplicate of https://github.com/nielsfaber/alarmo/issues/146

**Closed by nielsfaber** 2021-04-05 06:07 UTC
