### ISSUE TITLE
Error disarming...

### ISSUE THREAD

**Issue by wilotas** [nielsfaber/alarmo#393] opened 2022-02-08 23:22 UTC
### Alarmo Version

1.8.3

### HA Version

2022.2

### Bug description

Hi, 

I just tried to DISARM my alarm via my Master zone and I retrieve this:

![image](https://user-images.githubusercontent.com/513370/153092272-8fc01dd5-a43b-4809-a5de-2accf59642e4.png)

How can I fix it?

It has been working perfeclty during weeks.

**Comment by nielsfaber** [comment] 2022-02-09 06:59
Duplicate of #390

**Closed by nielsfaber** 2022-02-09 06:59 UTC
Labels: bug
