### ISSUE TITLE
Entry Delay Audio Alert

### ISSUE THREAD

**Issue by hubbyboo** [nielsfaber/alarmo#599] opened 2022-10-28 22:48 UTC
Feature/ work around request: 

Sound a entry delay countdown audio file to play from internal speakers on select tablets running the HA app.

On more traditional alarm systems, away mode entry delays commonly have an audio que to alert the end user that not only is the alarm system armed, but you need to disarm it before an intrusion alarm is triggered. The audio que stops playing once the system is disarmed.

I've Googled this quite extensively and scoured the forums but have not come across a straight forward solution. My apologies if one already exists and I missed it. I've come across some examples of people triggering Alexa dots/ Chromecasts, Sonos, ect with shared network files but I'm looking to play the audio from tablet speakers that are being used as wall mounted Alarmo keypads/ HA dashboards. 

Thanks in advance for any replies, I really appreciate the HA community and Alarmo is a fantastic addition.

**Comment by nielsfaber** [comment] 2022-11-06 17:31
Duplicate of https://github.com/nielsfaber/alarmo/issues/582

**Closed by nielsfaber** 2022-11-06 17:31 UTC
Labels: feature_request

**Comment by nielsfaber** [comment] 2022-11-06 17:36
Please copy your post to the request linked above.
For me it's pretty unclear how to implement sounds in alarmo, since alarmo does not run on a dedicated device. I think it could trigger the playing/casting of an MP3 file (or similar) to a media_player entity linked to HA, is this what you're looking for?
Please elaborate on this in your post.
