### ISSUE TITLE
Blank acctions after update

### ISSUE THREAD

**Issue by smic717394** [nielsfaber/alarmo#372] opened 2022-01-15 22:20 UTC
### Alarmo Version

V1.8.2

### HA Version

2021.12.9

### Bug description

After updating to 1.8.2, the acctions I had, no longer works. If I go to the the accion tab, all the acctions are still there but if I click any, the page is just blank. 

It is true that for most I use the yaml code for example one of the acction is the code bellow, that will run a script to sound a siren.

`- service: script.turn_on
  entity_id: script.1581864887624
  service_data: {}`

**Comment by nielsfaber** [comment] 2022-01-16 06:13
Duplicate of #369

**Closed by nielsfaber** 2022-01-16 06:13 UTC
Labels: bug
