### ISSUE TITLE
Alarmo not appears in itegration menu

### ISSUE THREAD

**Issue by JordiPF** [nielsfaber/alarmo#389] opened 2022-02-08 14:57 UTC
### Alarmo Version

v1.8.4

### HA Version

2022.2.3

### Bug description

I've downloaded alarmo and card from HACS and rebooted home assistant. I go to integration menu and search alarmo but it not appears in list and i can't continue.

![alarmo](https://user-images.githubusercontent.com/97964280/153012696-b5983900-f10b-4ab5-9b50-c7c005fa3760.jpg)
.

**Comment by nielsfaber** [comment] 2022-02-08 19:06
Duplicate of #387

**Closed by nielsfaber** 2022-02-08 19:06 UTC
Labels: bug
